### ISSUE TITLE
Content Picker - Prevent Drill In to Folders

### ISSUE THREAD

**Issue by DaleyKD** [box/box-ui-elements#1080]
**Describe the solution you'd like**
Ideally, I'd love a boolean set to false that would allow us to just display a root folder and select folders within that root folder WITHOUT letting the user drill in.

**Describe alternatives you've considered**
I was digging into the source code, looking for a solution and nothing became apparent.  I guess I'll have to write my own custom tree for now.

**Additional context**
I'm just a developer trying to use this for our 3rd party app.

**Comment by jeremypress** [comment]
Hi @DaleyKD,
We previously had an Element that functioned like a tree, but deprecated it due to a lack of usage by developers. Here's the source code if you're interested in repurposing some of it for your app. https://github.com/box/box-ui-elements/pull/612/files

**Comment by DaleyKD** [comment]
@jeremypress - Greatly appreciated.  However, it appears that the Content Tree was only single select?  The allure of Content Picker is multi-select.  Our use-case for now is asking the user to select 0...n folders that are in the specified base folder.

**Comment by jeremypress** [comment]
No problem. I think in this case since it's a pretty specific tweak I would recommend a CSS solution (similar to your other issue about hiding search). 

Here's a codepen example where I disabled clicks on the button we wrap each item in. It's not ideal, but it doesn't seem to conflict with any other buttons on the page.

https://codepen.io/anon/pen/JVNzWj

**Comment by DaleyKD** [comment]
DUDE!  I must be getting too old for this stuff.  I've never seen the CSS property 'pointer-events.' Also, I didn't even think that those DOM elements would be buttons.  I had just assumed they were anchors.

I'll demo this to my superiors and see if it suffices.  YOU ROCK!

**Comment by DaleyKD** [comment]
This appears to work best for our needs: https://codepen.io/anon/pen/vMmPqJ

**Comment by jeremypress** [comment]
Glad this works for you! I'm going to close this and the search issue out for now. If we see more requests for either of these we'll investigate a solution built into the library.
