### ISSUE TITLE
Content Picker - Hide Search Bar

### ISSUE THREAD

**Issue by DaleyKD** [box/box-ui-elements#1081]
**Describe the solution you'd like**
Ideally, I'd love a boolean set to false that would prevent the rendering of the search control.

**Describe alternatives you've considered**
Use jQuery or CSS to hide/remove the .be-search element.

**Additional context**
I'm just a developer trying to use this for our 3rd party app.

**Comment by jeremypress** [comment]
Recommending the CSS approach for now. If this request see significant traction we'll investigate adding a JS option.
