### ISSUE TITLE
Allow ContentSidebar to be disabled in ContentPreview

### ISSUE THREAD

**Issue by ccummings** [box/box-ui-elements#1106]
**Describe the solution you'd like**
Ability to render the`<ContentPreview>` component without the `<ContentSidebar>` being visible. Similar to how the thumbnail preview can be disabled.

**Describe alternatives you've considered**
- Staying on v9.9.1
- Monkey patching `ContentPreview` which I'd rather not do

**Comment by jeremypress** [comment]
Hi @ccummings,

To prevent the sidebar from rendering in ContentPreview, make sure you're not passing in any `contentSidebarProps`. Here's an [example using the es6 wrapper](https://codepen.io/box-platform/pen/Nmyemg), but in the react case you would just omit the prop passed into `ContentPreview`

**Comment by ccummings** [comment]
Looks like the issue is that `ContentSidebar` is throwing an error so it shows up anyways. Here's a demo of that: https://codesandbox.io/s/21x1242l8p

`ContentSidebar` is calling `setElementsDebugInfo` defined in `[src/utils/global.js](https://github.com/box/box-ui-elements/blob/master/src/utils/globals.js#L3)`. The `__VERSION__` isn't being replaced by Webpack so it errors.

Locally, I changed `__VERSION__` to an actual value and everything worked as you described.

**Comment by jeremypress** [comment]
Thanks for reporting, reverting the bad commit here https://github.com/box/box-ui-elements/pull/1109

**Comment by jeremypress** [comment]
Can you confirm this is fixed in 10.1.0?
