### ISSUE TITLE
ContentUploader errors

### ISSUE THREAD

**Issue by holbrookab** [box/box-ui-elements#117]
Hi,

I'm trying to leverage this library in my app (running react 16), I'm getting the following warning:

```Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `DroppableComponent`.
    in Unknown (created by DroppableComponent)
    in DroppableComponent (created by ContentUploader)
    in div (created by ContentUploader)
    in IntlProvider (created by Internationalize)
    in Internationalize (created by ContentUploader)
    in ContentUploader (created by Measure)
    in Measure (created by _class)
    in _class (created by _class)
```

Furthermore, the upload feature actually isn't working and I'm getting "A network error has occurred while trying to upload".

**Comment by priyajeet** [comment]
Try with React 15.x, we haven't upgraded/tested with the latest release of React 16.
I probably should fix the peerDeps to say React 15.x only atm.

**Comment by holbrookab** [comment]
Yeah I don't think I can use 15.x...our application will likely break.  Honestly I'm not familiar enough to know the problem other than "PureComponent" seems to be replaced with "Unknown"...which is weird.

**Comment by holbrookab** [comment]
BTW other components (e.g. Explore,, the Directory viewer), seem to work okay

**Comment by priyajeet** [comment]
My commit above seems to fix the error you were getting...

**Comment by holbrookab** [comment]
Oh, fast.  Let me try :)

**Comment by holbrookab** [comment]
Yes, warning goes away.  However, still getting the network error (yet not seeing any networking .  Any ideas?

```import React, { Component } from 'react';
import { t } from 'lib/i18n';
// Box Uploader content
import { addLocaleData } from 'react-intl';
import enLocaleData from 'react-intl/locale-data/en';
import { ContentUploader  } from 'box-ui-elements';
import messages from 'box-ui-elements/i18n/en-US';
import 'box-ui-elements/dist/uploader.css';

addLocaleData(enLocaleData);

export default class Uploads extends Component {
  render() {
    return (
      <div className="page">
        <h1>{t('uploads.title')}</h1>
        <ContentUploader 
            token='AUTH_TOKEN_REMOVED'
            language='en-US'
            messages={messages}
        />
      </div>
    );
  }
}
```

**Comment by priyajeet** [comment]
Going to check...

**Comment by priyajeet** [comment]
I think I found the issue. We aren't defaulting to `"0"` as the default upload folder.
To fix this temporarily in your code, pass in a `rootFolderId` prop for now.

```js
<ContentUploader
            rootFolderId='0'
            token='AUTH_TOKEN_REMOVED'
            language='en-US'
            messages={messages}
        />
```

**Comment by priyajeet** [comment]
New version 2.1.4 published.
