### ISSUE TITLE
Content Explorer: Cancel upload at 100% status --> file will be loaded but upload eventListener will not fired

### ISSUE THREAD

**Issue by tagiroff17** [box/box-ui-elements#1174]
We use Box ContentExplorer in our application (version: https://cdn01.boxcdn.net/platform/elements/9.1.1/en-US/explorer.js).

Today we faced with the issue, while trying to upload file. Here is the use case:

1) Uploading file. 
2) When it comes to 100% - Click "Cancel Uploads" button or the "x", near the status bar. (see attachment) 
![image](https://user-images.githubusercontent.com/29756235/57135699-04e1ef00-6db3-11e9-84d3-775b9a6fc115.png)
3) File will be uploaded anyway into repository, but contentExplorerEventListener "onupload" will not be fired in this case.

**Environment:**

ContentExplorer 9.1.1

**Desktop (please complete the following information):**

- OS: Windows 7
- Browser: Chrome
- Browser Version: 73.0.3683.103 (Official Build) (64-bit)

**Expected behavior**

Is it possible somehow fix the problem, e.g. disable button "Cancel Uploads" and hide "x" when 100% upload status?
We have some post-processing work on file which is fired by "onupload" eventListener and in this case we lose this processing.

**Comment by jstoffan** [comment]
Hi @tagiroff17. We were able to address this issue with #1511: the cancel button will now be disabled once the file reaches 100%. This change was released as part of [v11.0.0-beta.52](https://github.com/box/box-ui-elements/releases/tag/v11.0.0-beta.52%40master). 

Thanks for your patience.
