### ISSUE TITLE
Content Explorer not uploading files in Chrome, Firefox and eDGE

### ISSUE THREAD

**Issue by mremigio** [box/box-ui-elements#1181]
PLEASE THIS IS URGENT.  OUR PROD SYSTEMS ARE AFFECTED

**Environment:**
Windows Server 2012 R2
64 Bit OS
IIS 
ASP.NET MVC .NET Framework 4.6
Chrome 74.0.3729.131
Firefox 66.0.3
eDGE 41.162999

**Steps to reproduce the problem:**
We are using the Content Explorer Java Script libraries: 

<script src="https://cdn01.boxcdn.net/platform/elements/6.0.0/en-US/explorer.js"></script>
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=es6,Intl"></script>
<link rel="stylesheet" href="https://cdn01.boxcdn.net/platform/elements/6.0.0/en-US/explorer.css" />

and suddenly we experienced issues uploading files using Chrome, Firefox and eDGE.
It is still working fine using IE11.  We started to see this issue yesterday, 5/6.  Before 5/6, the Content Explorer was uploading documents just fine.

We receive an error:  "Something went wrong with the upload. Please try again."

**What is the expected behavior? (Screenshots can be helpful here)**

The Content Explorer should upload the documents using any browser.

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**

We receive an error:   "Something went wrong with the upload. Please try again."

**Link to application or sample code:**

I will attach our code

**If relevant, link to file (or attach file here)**
![BoxErrorWhenUploadingviaChrome](https://user-images.githubusercontent.com/14659790/57317207-6ef8dd80-70ac-11e9-9d8e-f88e51f98fb2.png)

Example Code:

<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="utf-8" />
    <title>Box Uploader</title>

    
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=es6,Intl"></script>

    
    <link rel="stylesheet" href="https://cdn01.boxcdn.net/platform/elements/6.0.0/en-US/explorer.css" />

    <style>
        .be-sub-header .be-breadcrumbs .be-breadcrumb .btn-plain {
            display: none;
        }

        .be-app-element .be-header {
            display: none;
        }
    </style>

    <script type="text/javascript" src="../Scripts/jquery-1.10.2.js"></script>
    <script type="text/javascript" src="../Scripts/jquery-1.10.2.min.js"></script>

    <script type="text/javascript">

        var _folderId;
        var _kk;
        var _asUser;
        var _cD;
        var _canUpload;
        var _BOXAccountDefaultUser;
        var _ORISDefaultUser;
        var _docAssociatedData;
        var _siteBaseURL;
        var _docORISResponse;
        var _fundNum;
        var _fundId;
        var _instNum;
        var _docType;
        var _removeTracking;

        function getUrlParameter(name) {
            name = name.replace(/[\[]/, '\\[').replace(/[\]]/, '\\]');
            var regex = new RegExp('[\\?&]' + name + '=([^&#]*)');
            var results = regex.exec(location.search);
            return results === null ? '' : decodeURIComponent(results[1].replace(/\+/g, ' '));
        };

        _folderId = getUrlParameter("folder");
        _kk = getUrlParameter("kk");
        _asUser = getUrlParameter("asUser");
        _cD = getUrlParameter("cD");
        _cU = getUrlParameter("cU");
        _BOXAccountDefaultUser = getUrlParameter("BxDU");
        _ORISDefaultUser = getUrlParameter("ODU");
        _docAssociatedData = getUrlParameter("docData")
        _siteBaseURL = getUrlParameter("siteURL");
        _fundNum = getUrlParameter("fN");
        _fundId = getUrlParameter("fI");
        _instNum = getUrlParameter("iN");
        _docType = getUrlParameter("dT");
        _removeTracking = getUrlParameter("rT");

        function getFolderId() {
            return _folderId;
        }

        function getKK() {
            return _kk;
        }

        function getAsUser() {
            return _asUser;
        }

        function getBoxAccountDefaultUser() {
            return _BOXAccountDefaultUser;
        }

        function getORISDefaultUser() {
            return _ORISDefaultUser;
        }

        function getCanDelete() {
            if (_cD == "true") {
                return true;
            }
            else {
                return false;
            }
        }

        function getCanUpload() {
            if (_cU == "true") {
                return true;
            }
            else {
                return false;
            }
        }

        function isIE() {
            if ((navigator.userAgent.indexOf("MSIE") != -1) || (!!document.documentMode == true)) //IF IE > 10
            {
                return true;
            }  
            return false;
        }

        function getDocAssociatedData() {
             return _docAssociatedData;
        }

        function getSiteBaseURL() {
            return _siteBaseURL;
        }

        function getORISResponse() {
            return _docORISResponse;
        }

        function getFundNumber() {
            return _fundNum;
        }

        function getFundId() {
            return _fundId;
        }

        function getInstitutionNumber() {
            return _instNum;
        }

        function getDocType() {
            return _docType;
        }

        function getRemoveTracking() {
            if (_removeTracking == "1") {
                return true;
            }

            return false;
        }

        function getORISBoxUserInfo(modelData) {

            var postBackURL;
            postBackURL = getSiteBaseURL() + "/" + "UploadDocuments" + "/" + "GetORISFileInfo";

            $.ajax({
                url: postBackURL,
                method: 'POST',
                data: JSON.stringify(modelData),
                contentType: 'application/json',
                dataType: 'json',
                async: false,
                success: function (data) {
                    _docORISResponse = data;
                },
               
            })
            //.done(function (data) {
            //    _docORISResponse = data;
            //    alert(JSON.stringify(getORISResponse()));
            //})

        }

        function addMetaData(modelData) {

            var postBackURL;
            postBackURL = getSiteBaseURL() + "/" + "UploadDocuments" + "/" + "AddMetaData";

            $.ajax({
                url: postBackURL,
                method: 'POST',
                data: JSON.stringify(modelData),
                contentType: 'application/json',
                dataType: 'json',
                async: false,
                success: function (data) {
                  
                },
            })
        }

        function getMetaData(modelData) {

            var postBackURL;
            postBackURL = getSiteBaseURL() + "/" + "UploadDocuments" + "/" + "GetMetaData";

            $.ajax({
                url: postBackURL,
                method: 'POST',
                data: JSON.stringify(modelData),
                contentType: 'application/json',
                dataType: 'json',
                async: false,
                success: function (data) {
                    _docORISResponse = data;
                },

            })
        }

        function decrementDocumentCount(modelData) {

            var postBackURL;
            postBackURL = getSiteBaseURL() + "/" + "UploadDocuments" + "/" + "DecrementDocumentCount";

            $.ajax({
                url: postBackURL,
                method: 'POST',
                data: JSON.stringify(modelData),
                contentType: 'application/json',
                dataType: 'json',
                async: false,
                success: function (data) {
                    if (getRemoveTracking() == true) {
                        window.location.reload();
                    }
                },
            })
        }

        function getMetaDataList(modelData) {

            var postBackURL;
            postBackURL = getSiteBaseURL() + "/" + "UploadDocuments" + "/" + "GetMetaDataList";

            $.ajax({
                url: postBackURL,
                method: 'POST',
                data: JSON.stringify(modelData),
                contentType: 'application/json',
                dataType: 'json',
                async: false,
                success: function (data) {
                    _docORISResponse = data;
                },
            })
        }
      
    </script>
</head>
<body>
    <div class="container" style="height:475px;width:100%;">
        
        <script src="https://cdn01.boxcdn.net/platform/elements/6.0.0/en-US/explorer.js"></script>
      
        <script>
            var folderId = getFolderId(); 
            var kk = getKK(); 
            var contentExplorer = new Box.ContentExplorer();

            var addExtraHeaders = function (config) {
                config.headers['As-User'] = getAsUser();
                return config;
            };

            function findSimpleMeta(listMetaData, fileId) {

                var simpleData = {};
                for (var k = 0; k < listMetaData.length; k++) {
                    if (listMetaData[k].FileId == fileId) {
                        simpleData['FileId'] = fileId;
                        simpleData['ModifiedDate'] = listMetaData[k].ModifiedDate;
                        simpleData['ModifiedBy'] = listMetaData[k].ModifiedBy;
                        break;
                    }
                }

                return simpleData;

            }

            var modifyResponse = function (response) {

                if ((response.config.method == 'get') && (response.data.item_collection != null)) {

                    var numDocuments = response.data.item_collection.entries.length;
                    var listOfData = [];
                    for (var i in response.data.item_collection.entries) {
                        //if (response.data.item_collection.entries[i].modified_by.name.trim() == getBoxAccountDefaultUser().trim()) {
                        //    response.data.item_collection.entries[i].modified_by.name = getORISDefaultUser();
                        //}

                        //Get ORIS Box Info
                        var simpleData = {
                            FileName: response.data.item_collection.entries[i].name,
                            DocData: getDocAssociatedData(),
                            ModifiedDate: response.data.item_collection.entries[i].modified_at,
                            ModifiedBy: response.data.item_collection.entries[i].modified_by.name,
                            FileId: response.data.item_collection.entries[i].id
    
                        };

                        //getMetaData(simpleData);
                        //var orisResponse = getORISResponse();
                        //response.data.item_collection.entries[i].modified_at = orisResponse["ModifiedDate"];
                        //response.data.item_collection.entries[i].modified_by.name = orisResponse["ModifiedBy"];

                        //Add to list
                        listOfData.push(simpleData);
                    }

                    getMetaDataList(listOfData);
                    var listRetData = getORISResponse();
                    
                    for (var i in response.data.item_collection.entries) {
                        var metaData = findSimpleMeta(listRetData, response.data.item_collection.entries[i].id);
                        response.data.item_collection.entries[i].modified_at = metaData["ModifiedDate"];
                        response.data.item_collection.entries[i].modified_by.name = metaData["ModifiedBy"];

                        if (getRemoveTracking() == true) {
                            if (numDocuments == 1) {
                                response.data.item_collection.entries[i].permissions.can_delete = false;
                            }
                        }
                    }
                }
                
                return response;

              
            }
           
            contentExplorer.show(folderId, kk, {
                container: '.container',
                logoUrl: 'box', 
                defaultView: 'files',
                canRename: false,
                canCreateNewFolder: false,
                canShare: false,
                canSetShareAccess: false,
                canPreview: true,
                canDownload: true,
                canDelete: getCanDelete(),
                canUpload: getCanUpload(),
                requestInterceptor: addExtraHeaders,
                responseInterceptor: modifyResponse,
                sortBy: 'modified_at',
                sortDirection: 'DESC',
                size: 'small'

            });

            contentExplorer.addListener('upload', function (arrFiles) {

                //Post Meta Data
                for (var i in arrFiles) {
                   
                    //Post Meta Data to Service
                    var metaData = {
                        DocType: getDocType(),
                        FileName: arrFiles[i].name,
                        FileId: arrFiles[i].id,
                        InstitutionNumber: getInstitutionNumber(),
                        FundNumber: getFundNumber(),
                        FundId: getFundId(),
                        AssociatedId: getDocAssociatedData(),
                        FolderId: getFolderId()
                    };

                    addMetaData(metaData);
                }
               
            });

            contentExplorer.addListener('delete', function (arrFiles) {
            
                for (var i in arrFiles) {

                    //Decrement Document Count
                    var metaData = {
                        DocType: getDocType(),
                        FileName: arrFiles[i].name,
                        FileId: arrFiles[i].id,
                        InstitutionNumber: getInstitutionNumber(),
                        FundNumber: getFundNumber(),
                        FundId: getFundId(),
                        AssociatedId: getDocAssociatedData(),
                        FolderId: getFolderId()
                    };

                    decrementDocumentCount(metaData);
                }
            });

        </script>

        <script type="text/javascript">
                    
        </script>
    </div>
</body>
</html>

**Comment by ConradJChan** [comment]
Hi @mremigio, I've created a codepen with the Content Explorer 6.0.0 (https://codepen.io/conradchan/pen/xNGPMY) which appears to successfully upload files in both Chrome and Firefox.

Could you provide a HAR file for further debugging?

**Comment by mremigio** [comment]
Hi ConradJChan:
I tried your code pen and it won't allow me to upload files.
What is a HAR file ?
Thanks

**Comment by mremigio** [comment]
Also, this was not an issue until yesterday.  Did something change yesterday ?

**Comment by mremigio** [comment]
Also, we can successfully upload documents using IE 11

**Comment by ConradJChan** [comment]
Sorry I should have been more clear. In the codepen, you'll need to update the `folderId` and `accessToken` on lines 21 and 22.

There were no changes to Content Explorer since you are using version 6.0.0, but perhaps the v2 API endpoints were misbehaving potentially? However, no incidents were reported yesterday (https://status.box.com/)

This link describes how to capture a HAR file: https://community.box.com/t5/Managing-Content-Troubleshooting/How-to-Generate-a-HAR-File-in-Chrome-IE-Firefox-and-Safari/ta-p/366

**Comment by mremigio** [comment]
Hi ConradJChan:
The issue seems to be fixed now. What was the fix ?
I have the HAR file but this site won't allow me to attach it ?

Thanks

**Comment by mremigio** [comment]
[BoxUploadHAR.log](https://github.com/box/box-ui-elements/files/3154038/BoxUploadHAR.log)
Here's the HAR file.  Seems I just needed to rename it.

**Comment by ConradJChan** [comment]
There was some issue affecting a subset of customers but it appears to be resolved now. Closing the issue
