### ISSUE TITLE
Preview Close button not working on Explorer

### ISSUE THREAD

**Issue by holbrookab** [box/box-ui-elements#120]
I'm trying to leverage the ContentExplorer component.  When I go to preview a file, I can't seem to return back to the Explorer view.

In this case, should the preview automatically close and you go back to the explorer view?

**Comment by holbrookab** [comment]
Looking at the React debugger, it appears the `isOpen` prop for the `PreviewDialog` is set from `true` to `false`...however that doesn't close the box.

**Comment by holbrookab** [comment]
https://github.com/box/box-ui-elements/blob/eedf560810f9c595ea6a6a69a1a6bdd4276ad5df/src/components/ContentExplorer/PreviewDialog.js#L58

Should that do something other than return null?  Do we need to somehow destroy or hide the `PreviewDialog`?

**Comment by tonyjin** [comment]
![2017-11-17_16-46-52](https://user-images.githubusercontent.com/689351/32974884-ee1fb7c4-cbb6-11e7-8f60-7f458bbfdb85.png)

Does the close button in the upper right corner not work?

**Comment by holbrookab** [comment]
Not for me.  When I removed the "isOpen" like in the PR, it worked.

**Comment by priyajeet** [comment]
@holbrookab Can you submit the CLA form https://developer.box.com/docs/box-sdk-cla

**Comment by holbrookab** [comment]
Done

**Comment by priyajeet** [comment]
Thanks
