### ISSUE TITLE
i18n: need to use plural format for string be.taskShowMoreAssignees

### ISSUE THREAD

**Issue by ehoogerbeets** [box/box-ui-elements#1337]
The new string be.taskShowMoreAssignees in src/elements/common/messages.js formats a number into the string, but does not use a proper plural syntax. This is not translatable to many languages.

**Environment:**

- Elements version: 11.0.0-beta.20

**Steps to reproduce the problem:**

String in the source code is 

'Show {additionalAssigneeCount} More'

It should be something like:

'{additionalAssigneeCount, plural, one {Show {additionalAssigneeCount} More} other {Show {additionalAssigneeCount} More}'

**Comment by alexkrolick** [comment]
Copying to internal issue tracking
