### ISSUE TITLE
Box Content Explorer File Preview Icon Error

### ISSUE THREAD

**Issue by thechrisdeg** [box/box-ui-elements#139]
We are having a problem with the Content Explorer element that the icon to the left of a file name is showing up as an AI icon file type regardless of what the file actually is, with the exception of PDF files which show up with the PDF icon. 

I went ahead and made a screen share video that provides better insight and hopefully can explain/show the problem and use case better than I can. This video was originally made for a support agent with the Box API team so please disregard the names I say. 

Here is the link to the screen share video: https://lda.agency/box-case_1569164

Below is our developer's explanation for reference as to how we are utilizing the element:
We have implemented our needs with Box using the Box Content Explorer and setting the canUpload parameter to true. We then generated site-wide tokens using the OAuth 2 standard. Finally, we downscoped the tokens so that each user can only see the folder they have been given access to.

Please let me kow how to proceed.

**Comment by tonyjin** [comment]
Thanks for the report. That link is currently blocked by our corporate firewall, could you please try uploading the file to Box or GDrive to share?

Can you please also share what version number of the Content Explorer you're using? Also are you using it as a React component or as an ES6 library? What file types are you seeing the 'AI' file icon fore?

I see one instance of the issue on our demo page (https://codepen.io/box-platform/pen/wdWWdN) since both the 360 image and JPG show an 'AI' file icon, but the MP3, MP4, and text files all show the correct icon.

**Comment by tonyjin** [comment]
Ah, just got access to the link. It looks like you're seeing similar things to me. This may be a bug with the FileIcon component we're relying on, we'll take a look thanks!

**Comment by thechrisdeg** [comment]
Hi, 

We are using the version 2.1.2 for our content explorer. 

We are using ES6, not React. We are noticing it on all file types, except PDF and videos (and AI of course). 

Thank you for any help! 





Chris Degenaars
Digital Strategy & Operations Manager
Long Drive Agency

p:	(972) 755-9471  m: +1 (214) 298-5388
w:	www.longdriveagency.com <http://www.longdriveagency.com/>
e: chris@longdriveagency.com <mailto:chris@longdriveagency.com>
 <https://www.facebook.com/thechrisdeg>   <https://twitter.com/thechrisdeg>   <https://www.linkedin.com/in/christopher-degenaars-24140a65/>   <https://www.instagram.com/thechrisdeg/>

**Comment by thechrisdeg** [comment]
Are there any updates on this issue? @tonyjin 

Thanks!

**Comment by tonyjin** [comment]
This will be fixed in our next CDN deployment, which should happen next week.

**Comment by tonyjin** [comment]
@thechrisdeg, this should be resolved with v3.4.1. The change log is located at https://github.com/box/box-ui-elements/releases. Thanks @wenboyu2 & @priyajeet for fixing this sooner!
