### ISSUE TITLE
Duplicate file upload in ContentUploader

### ISSUE THREAD

**Issue by manoj131990** [box/box-ui-elements#1433]
Please fill out the following template so we can reproduce and fix your issue as quickly as possible!

**Note:** if your issue includes a potential security vulnerability, please do not file it here. Instead, email the issue to security@box.com for support.

**Environment:**
Included 'box-ui-element' in React application and added ContentUploader to upload files to box cloud.

- Elements version:

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: All browsers
- Version: latest

**Steps to reproduce the problem:**
Select a file with browse functionality and and then Drag-Drop the same file in Content Uploader, both files can be seen in queue.

**What is the expected behavior? (Screenshots can be helpful here)**
If user selects a file with browse functionality and then drag-drops the same file, upload should be restricted, it will be helpful if user is shown a info message "File in Queue."  

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**

![uploader-issue](https://user-images.githubusercontent.com/53086611/61537358-9aa52600-aa54-11e9-8f3c-c5eb84f391dd.PNG)

**Comment by mickr** [comment]
Hey @manoj131990, I was able to recreate the issue on our end as well. We'll look into addressing this issue. Thanks for the report!
