### ISSUE TITLE
Content SideBar - with newAPI=true you can add a task but task descriptions do not show

### ISSUE THREAD

**Issue by amonier** [box/box-ui-elements#1461]
Using the sidebar element, we want to be able to add a new task and show the description.

**Note: When you add a new task, the description is visible for the new task, but disappears on refresh**

Versions Tested: v11.0.0-beta.36 and v10.1.0 

Using newAPI=true
- we can add a task (GOOD)
- the description does NOT show (BAD)

Using newAPI=false
- we can NOT add a task (BAD)
- the description shows (GOOD)

Content SideBar Configuration
    features: {
      activityFeed: {
        tasks: {
          createButton: true,
          // createFromComment: true,
          newApi: true,
          newCards: true
        },
      }
    }

![newAPI _True False comparison](https://user-images.githubusercontent.com/14241376/61841502-9b75f780-ae5a-11e9-92b4-516894470e07.png)

**Comment by ConradJChan** [comment]
Hi @amonier, thanks for opening the issue. 

I am able to reproduce the issue you're seeing with v10.1.0 however with v11.0.0-beta.36 the new task related feature flips are no longer supported and I am unable to see the issue you describe. Is going with v11.0.0-beta.36 an acceptable solution?

**Comment by amonier** [comment]
I think the screenshots I provided might have led to some confusion. 

The issue we are seeing is that the **task description/message is only available when the task is created**. So on refresh, or when another user goes to the Activity Feed the task description is no longer visible.  v11.0.0-beta.36

Steps to recreate
1/ add a new General Task to a document with a message "Here is your  task"
2/ the task message/description shows on sidebar  (GOOD)
3/ refresh sidebar, task description/message disappears 
REALLY BAD -- How does the user know what to do?? 

See the screenshot below taken using v11.0.0-beta.36

BTW: The task description/ message shows correctly in the Box UI.

![Missing description](https://user-images.githubusercontent.com/14241376/61962169-8e5a2500-af8e-11e9-9d20-eedb2faa7fb5.png)

**Comment by amonier** [comment]
@ConradJChan .. Our developer is reporting that everything is working fine now. It might have a been a cache issue.

Again, thanks for your quick response. This was a critical issue for us.

Alan
