### ISSUE TITLE
Error when using box-ui-elements with Meteor-React

### ISSUE THREAD

**Issue by coryma** [box/box-ui-elements#156]
I am using  [React in Meteor](https://guide.meteor.com/react.html) 1.6. to build Box application which I can generate Box access token on the server site and use the token on Box UI client by using Meteor DDP protocol

I am getting the following console errors following using every UI components of box-ui-elements in my project. 

I think this is because Import and export is not supported in Meteor and webpack 1.x like this issue [seeden/react-facebook#55](url). Can anyone help to solve it for box-ui-elements?

![image](https://user-images.githubusercontent.com/363297/34925305-81607848-f9e3-11e7-9192-f8614c12ccc5.png)

**Comment by tonyjin** [comment]
Thanks for the report. We haven't worked with Meteor before so we'll investigate and share what we find.

**Comment by fernandotrip** [comment]
Hi @coryma , can you fix the problem with meteor and box-ui ?

**Comment by coryma** [comment]
@fernandotrip I didn't fix it. I chose to build UI by myself rather than used box-ui-elements.
