### ISSUE TITLE
Content Explorer appears to have issues handling requests from forward proxies

### ISSUE THREAD

**Issue by sghosh326** [box/box-ui-elements#165]
Our software that embeds the Content Explorer does not allow upload or create new folder at a customer sites with a particular networking configuration. It works fine when the requests are from many different client sites. 

We know that the customer site does not block Box as a whole, because these operations works in the Box app.

The one difference I see in the cases where it does not work is that the requests are coming from a network that has deployed a forward proxy that returns an X-FORWARDED-FOR header with multiple IP as is standard for a lot of proxy servers. This X-FORWARDED-FOR is an example where it does not work: 10.26.6.155, 199.207.253.96

We have also create a support ticket with more details about the case.

Thanks for your help in resolving this issue.

**Comment by tonyjin** [comment]
Thanks for the report. This issue seems best suited for the support ticket you've already filed.
