### ISSUE TITLE
Recent versions of the release throws Javascript errors

### ISSUE THREAD

**Issue by sghosh326** [box/box-ui-elements#166]
I have tried several of the recent releases starting from 3.5.2 and going back to around 3.4.0. They all throw the following JS error. Is there a new dependency I am missing? 

I have been using the UI Elements for a while in a non-React app using the JS only versions of the components. My other dependencies are JQuery and Bootstrap. The working version I am on is 2.1.2.

The following are the error outputs in the Console on Chrome.
<WARNING>
The SSL certificate used to load resources from https://cdn01.boxcdn.net will be distrusted in M66. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

<ERROR>
explorer.js:1 Uncaught Error: Minified React error #40; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=40 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at p (explorer.js:1)
    at Object.unmountComponentAtNode (explorer.js:1)
    at t.value (explorer.js:1)
    at HTMLAnchorElement.<anonymous> (login:372)
    at HTMLAnchorElement.dispatch (jquery.min.js:3)
    at HTMLAnchorElement.r.handle (jquery.min.js:3)

**Comment by tonyjin** [comment]
Thanks for the report, we'll take a look. You can ignore the first warning, our operations team is aware and that will be resolved before M66 is released.

**Comment by sghosh326** [comment]
Hi Tony,

Sorry, did not see the edit earlier. I was working on a CodePen example but I could never get the CORS warning to go away. I added https://s.codepen.io and https://codepen.io in the CORS domains of my app and generated a developer access token. Tried this with 2 apps. The newly added origins did not seem to register with the Box system. 

Anyway, I have gotten it to work with 3.5.2. I am using the Content Explorer. Our use case is an external user is getting access to several shared folders. Since the Content Explorer only supports a single folder ID as the root folder, our initial page displays each of these shared folders and when each shared folder is selected, in the event handler we do a new Content Explorer and call the show method for it. I was instantiating the Content Explorer once and was calling hide() and then show() for each folder selected. It throws the error on the hide() call in recent versions of the component. I have adjusted to code to not call hide() and instantiate a new Content Explorer each time a folder is selected.

**Comment by sghosh326** [comment]
Ignore my last comment, it turns out I needed to code it the way I had it earlier, just added a check to call hide() if its not the first time and the content explorer has content loaded in it through a call to show(). I guess the code was more lenient earlier.

**Comment by tonyjin** [comment]
Glad you were able to fix it. If I'm reading this right, the Content Explorer cannot call `show()` after the first time without calling `hide()` first?

We can probably fix that if that's the case.

**Comment by sghosh326** [comment]
No the issue is Content Explorer cannot call hide() if it was previously not called with a show() and is rendering a folder. The first time around the content explorer has not rendered a folder and the hide() was getting called assuming we are switching from one folder to another. It used to be harmless in the earlier versions, maybe it is considered in-proper use now?
