### ISSUE TITLE
Cannot create a shared link by using content explorer

### ISSUE THREAD

**Issue by robertvu123** [box/box-ui-elements#1670]
**Environment:**

- Elements version: Content Explorer v10.1.0

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome Dev (64-bit)
- Version v79.0.3941.4

**Steps to reproduce the problem:**
1. Implement content explorer with default options.
2. Upload a file
3. Click Share button on the new file

**What is the expected behavior? (Screenshots can be helpful here)**
See a pop-up to get a shareable link
![image](https://user-images.githubusercontent.com/54953721/66877150-49c89f00-ef69-11e9-9169-7a7c8865413e.png)

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
Seeing a "None" text instead of a link
![image](https://user-images.githubusercontent.com/54953721/66876756-c65a7e00-ef67-11e9-89e3-b01d9903dae4.png)

**Additional context**
According to the documentation, content explorer supports sharing files, but it didn't work for me. I suspect that it has something to do with user type because the account that I used to get access token is an app user. I don't know what I'm missing here, please help.

**Comment by mxiao6** [comment]
Hi @robertvu123, thank you for sharing the info.
If you suspect it's the problem of account type, you can run `TOKE=xxx FOLDERID=xxx yarn start:examples` with the same access token to see if it works.
