### ISSUE TITLE
Request: pagination

### ISSUE THREAD

**Issue by holbrookab** [box/box-ui-elements#178]
Does this library leverage pagination at all (I know the API does)?

For example, could we limit the number of returned items via a parameter, and then have forward/advance buttons?

**Comment by tonyjin** [comment]
Thanks for the request. Are you asking for pagination in the Picker, Explorer, or both?

**Comment by holbrookab** [comment]
Both

Sent from my iPhone

On Feb 13, 2018, at 1:03 PM, Tony Jin <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the request. Are you asking for pagination in the Picker, Explorer, or both?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_box_box-2Dui-2Delements_issues_178-23issuecomment-2D365403015&d=DwMCaQ&c=yIH1_-b1hO27QV_BdDph9suDL0Jq0WcgndLmIuQXoms&r=jUAGgsing1fnEPbWkMIId9K2PH8u6zr9HI1ZUijsVZ0&m=00YMdlDaMFJ_hpfJV0oBz2ApvFYD0lCNDnQUEz5vKQI&s=vSgTzKy3oT1CK5GGdUubh-DXuP5sy38unf_Ws3TT6Q4&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHprLZTSyLtovMsLkZZGC-5Fas7eK4-5FjfUks5tUfhggaJpZM4SBrsC&d=DwMCaQ&c=yIH1_-b1hO27QV_BdDph9suDL0Jq0WcgndLmIuQXoms&r=jUAGgsing1fnEPbWkMIId9K2PH8u6zr9HI1ZUijsVZ0&m=00YMdlDaMFJ_hpfJV0oBz2ApvFYD0lCNDnQUEz5vKQI&s=IZo2sq-9peT3ms9vbTOTABlne-AXknLP5BhNtHbqzMQ&e=>.

+========================================================================+
This email is confidential and may be privileged. If you have received it
in error, please notify us immediately and then delete it.  Please do not
copy it, disclose its contents or use it for any purpose.
+========================================================================+

**Comment by Rikav** [comment]
Question - why is this seen as an enhancement? This should be classified as a bug. The Box Content Picker is unusable in our environment due to large amounts of content in our environment resulting in insane load times.

**Comment by NeilMeredith** [comment]
I agree with Rikav, pagination is critical here.  Taking 30+ seconds to load a folder with a large number of items in it is unacceptable to our end users and means I can't use the built in Box Content Explorer.  I think this should be prioritized as a bug as well.

**Comment by tonyjin** [comment]
Feedback noted. We have other priorities until the end of July and will take a look at this shortly after. If you're interested in making a PR, we'd be happy to review!

**Comment by NeilMeredith** [comment]
Thank you for adjusting the issue status.  I doubt I will have the time to put together a PR on this, but I'll check back on the status of this issue after July, thanks.

**Comment by jstoffan** [comment]
We recently added pagination support for ContentExplorer and ContentPicker in version 7.0.0.
