### ISSUE TITLE
Can we pass 'As-User' to the UI Element Explorer

### ISSUE THREAD

**Issue by mremigio** [box/box-ui-elements#191]
Hello:

I am a developer for UCLA and we are very interested in using the Box UI Elements Explorer and the Box UI Elements Uploader.  

Currently, the UI Element Explorer accepts a folder id and a token.  Is there a way for us to pass it the 
'As-User' ?  

If we cannot pass the Explorer the 'as-user', is there a way for us to add to the http headers ?

Thanks

Mila

**Comment by priyajeet** [comment]
Not at the moment, but soon(ish) you will be able to add a request interceptors as shown here https://github.com/axios/axios#interceptors.

**Comment by mremigio** [comment]
Hi Priyajeet:

Thank you for responding.  We are leaning heavily on using the Box UI Elements Explorer and Uploader directly instead of building a custom UI that interacts with your SDK.

Just to clarify, will the interface to the UI Elements Explorer be extended so that we can easily pass in 'As-User' or add to the http headers:

Sample Code:

 <script>
            var folderId = getFolderId(); //'0';
            var accessToken = getToken(); //'6UGMm8CkfB5AK0ao2sycdYRqeP0jUsrT';
            var contentExplorer = new Box.ContentExplorer();
            contentExplorer.show(folderId, accessToken, {
                container: '.container'
            });

</script>

Thanks

Mila

**Comment by priyajeet** [comment]
It will work like shown here https://github.com/box/box-ui-elements/pull/194

**Comment by mremigio** [comment]
Hi Priyajeet:

Do you know when the request Interceptors will be available ?  You specified 'soon(ish)', but, just curious if that means within the next month, 2 months, 6 months ?

Thank you,
Mila

**Comment by priyajeet** [comment]
Before end of next week

**Comment by mremigio** [comment]
That's wonderful Priyajeet. Thank you

Also, on a separate note,  how do we show the person that uploaded the document on the UI Content Explorer ?  I wrote a separate issue for this but no one has responded :-(  Thank you

**Comment by tonyjin** [comment]
@mremigio we'll respond in your other issue, please keep the discussion focused on the issue at hand.

**Comment by mremigio** [comment]
Will do tonyjin

**Comment by mremigio** [comment]
Hi Priyajeet:
Are the request Interceptors available ?
Thanks
Mila
