### ISSUE TITLE
localhost issue

### ISSUE THREAD

**Issue by git2g** [box/box-ui-elements#192]
- All of sudden, the `Content Uploader` widget is not working when requests are made from `localhost` but works fine when the same request (with the same codebase) is made from other domains in the CORS whitelist. Wondering if there were some additional changes made to requests originating from localhost that is causing the below issue

![image](https://user-images.githubusercontent.com/18152044/36689954-7e35296e-1af6-11e8-9602-b7e04af66e09.png)

![image](https://user-images.githubusercontent.com/18152044/36690080-e02baa30-1af6-11e8-8fd2-781642106f07.png)

![image](https://user-images.githubusercontent.com/18152044/36689668-b406da98-1af5-11e8-95e2-53510997451d.png)

**Comment by jeremypress** [comment]
Hey @git2g, 
Can you try removing the "s" from your whitelist? Unless you set it up specifically, localhost runs over HTTP.

**Comment by git2g** [comment]
My localhost has to make requests over `https` for SSO. And this has been working fine for a few weeks with all the ui-elements until this morning

**Comment by git2g** [comment]
Also, tried to use `0.0.0.0` and whitelisted that in CORS with no avail. Still getting `A network error has occurred while trying to upload` without any requests in the console.

**Comment by tonyjin** [comment]
Can you please share what version you're using, whether you're using the React component or ES6 wrapper, and describe your environment?

Thanks!

**Comment by tonyjin** [comment]
Closing since we haven't heard from you, but please reach out to https://support.box.com if you continue to have issues.
