### ISSUE TITLE
Content Explorer does not show Uploader name

### ISSUE THREAD

**Issue by mremigio** [box/box-ui-elements#193]
Hello:

We are using the UI Content Explorer and passing it a Token that was generated using the Admin Console

Sample Code:
 var folderId = '0';
 var accessToken = '6UGMm8CkfB5AK0ao2sycdYRqeP0jUsrT';
 var contentExplorer = new Box.ContentExplorer();
 contentExplorer.show(folderId, accessToken, {
                container: '.container'
  });

Currently, it doesn't look like the Content Explorer shows the user that uploaded the document.
How to we show the user that uploaded the document ?

Thanks

Mila

**Comment by mremigio** [comment]
Hello:

Any luck with this ?

Thanks

Mila

**Comment by tonyjin** [comment]
See: https://developer.box.com/docs/box-content-explorer#section-events

The Content Explorer will fire an event `upload` with an array of uploaded file objects. You can display a notification or message after receiving that event.

**Comment by mremigio** [comment]
Hi Tonyjin:

Thank you for your response.
I would like to display the name of the user that uploaded the document in the UI Content Explorer alongside the uploaded date.  Currently, Content Explorer only shows the uploaded date.
If I listen to an event, then I will have to build a separate screen.

Please advise.
Thanks
Mila

**Comment by tonyjin** [comment]
Ah I see, I misinterpreted your request. I renamed the issue so it's clearer for us that this is a feature request.

**Comment by mremigio** [comment]
Thank you very much Tonyjin.    Do you know when this feature will be implemented ?  I'm asking because we cannot go live without it and our project manager wants to know timeline.  Thanks

**Comment by oTMHCC** [comment]
Just leaving a tip. I had the same issue. I changed my code to generate a user token instead of an admin token, and in that case it showed the name of the user instead of the app when uploads are done.

**Comment by mremigio** [comment]
Thanks oTMHCC.  For some reason, ours, doesn't even show the name of the app.

**Comment by mremigio** [comment]
Hi Tonyjin:
Does the token type (admin vs user) dictate whether the username shows up on the Content Explorer ?
We are passing an admin token.  But, even when passing an 'admin token' we are not seeing the name of the app as the username.
Thanks
Mila

**Comment by sghosh326** [comment]
We needed this feature as well. I have implemented this in a feature branch off my fork and have submitted the following pull request:
https://github.com/box/box-ui-elements/pull/203

**Comment by mremigio** [comment]
Thanks sghosh326

**Comment by mremigio** [comment]
Hello:
Just checking to see when this feature will be ready :-)
Thank you

**Comment by tonyjin** [comment]
We have other work scheduled and don't have a timeline for when we're going to get to this. @sghosh326 graciously put up a pull request but there are some issues to solve before we can merge. If you have some time, it seems like sghosh326 is okay with someone fixing the pull request to get it merged.

**Comment by sghosh326** [comment]
Looks like @priyajeet has implemented this in https://github.com/box/box-ui-elements/pull/209
for release 4.1.
I haven't pulled the latest but you can try getting 4.1 or 4.2 and see if its there

**Comment by tonyjin** [comment]
Correct me if I'm wrong, but you really need who created the file, aka uploaded it, not who modified it right @mremigio?

**Comment by mremigio** [comment]
sghosh326:

I am using 4.1 (JavaScript Agnostic libraries) and I am not seeing the name of the person that uploaded the file.  Perhaps it is in 4.2, but, I don't think version 4.2 is available yet in the JavaScript agnostic libraries.

tonyjin:

We just need the person that uploaded the file and if it is modified, then who modified it.
If someone modifies it, then the name of the modifier should replace the name of the person that originally uploaded the file.  

Thanks

Mila

**Comment by sghosh326** [comment]
@mremigio ,

Just to be clear, you are expecting the Modified column to show the last user who modified the file like it shows in Box, correct? When I looked at this change:
https://github.com/box/box-ui-elements/commit/bf74d5f
in 4.1, it appears thats what the code is doing. There is some responsive stuff in there, so maybe you might need to resize your window? This change is a lot more sophisticated that the pull request I sent. If you are not building from source, I can send you my explorer.js , but my base is 3.6.2. 

-Sandip

**Comment by mremigio** [comment]
Sorry sghosh326, my bad.  We are currently using v4.0.1 (https://cdn01.boxcdn.net/platform/elements/4.0.1/en-US/explorer.js)

Tonyjin:

When will version 4.1 or 4.2 be available in javascript ?

Thank you,

Mila

**Comment by mremigio** [comment]
Hi Tonyjin:
Do you know when version 4.1 or 4.2 will be available in the 'JavaScript agnostics libraries' ?
Thanks

**Comment by priyajeet** [comment]
Its now live with version 4.3.2, thanks.

**Comment by mremigio** [comment]
Thank you priyajeet.
