### ISSUE TITLE
Content Uploader uses a hardcoded root folder folder ID for preflight

### ISSUE THREAD

**Issue by jasonpan12** [box/box-ui-elements#200]
Hiya folks!

On the latest 3.5.2 of the Content Uploader, when uploading a document (testable with https://codepen.io/box-platform/pen/QvqGwr) one of the preflight OPTIONS calls uses the following body:

```{
"name": "test_name",
"parent": {
"id": "0"
  },
"size": "10"
}
```
This appears to be hardcoded from here:
https://github.com/box/box-ui-elements/blob/701a2c0ba3331c83fc2c6034f4a970701d4f7aee/src/api/uploads/UploadReachability.js#L109

Enterprises which have root content creation disabled will get a 404 error on this call, so any applications or which watch for errors will catch that too.

This could be fixed by changing the folder ID to accept the one that was passed in the element, or reconsidering whether this particular preflight is necessary.

Thanks,
Jason

**Comment by wenboyu2** [comment]
Thanks for reporting this issue, we'll look into it.
Wenbo
