### ISSUE TITLE
Getting error on IE 11 with Content Explorer

### ISSUE THREAD

**Issue by oTMHCC** [box/box-ui-elements#202]
I posted this in the developer forum but thought I might have better success here.

This has been working ok, until recently. The code below for displaying content explorer works fine in Google Chrome and Microsoft Edge, but I'm getting this error in IE.

Any pointers on what is breaking, please?

![box ui content explorer](https://user-images.githubusercontent.com/33462451/37006711-77720690-208e-11e8-848b-b472f371985a.png)

**Comment by priyajeet** [comment]
Can you try with the polyfill script before any other script? thanks

**Comment by oTMHCC** [comment]
That did the trick! Thanks
