### ISSUE TITLE
Upload cleanup

### ISSUE THREAD

**Issue by priyajeet** [box/box-ui-elements#204]
Things to do
- Use axios (if possible) for Xhr.uploadFile()
- Cleanup PlainUpload.uploadErrorHandler
- Maybe tweak the MultiPut commit retry timeout to be lower (right now its header `retry-after` * 1000)

**Comment by tonyjin** [comment]
I know for some API endpoints, the `Retry-After` header sets some arbitrary number, but the multi-put commit retry returns different values at different times, suggesting we should follow it.
