### ISSUE TITLE
No visual separation between file size and uploaded username in content picker

### ISSUE THREAD

**Issue by chantellelee** [box/box-ui-elements#2185]
- Elements version: 2.5.3
- OS: Windows 10 
- Browser:
Chrome (81.0), 
Firefox (77.0.1), 
Edge (42.17), 
IE (11.13)

**What is the expected behavior? (Screenshots can be helpful here)**
Like the content explorer, the "modified by name" and the file size are separated by a '-'
ex. modified by Joe - 2 KB

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
The Content Picker does not have this separation so the file size is appended to the user name

**Link to application or sample code:**
This can be reproduced in the sample Box provides https://codepen.io/box-platform/pen/PWPxBm

**Expected behavior**
Please match the styling of the content explorer or add a space

![screenshot](https://user-images.githubusercontent.com/38863053/84408431-5caf7400-abc9-11ea-965a-c5b3195dac07.png)

**Comment by sahiga** [comment]
Hi @chantellelee, thank you for the report. This bug has been fixed in Elements v13.0.0.
