### ISSUE TITLE
Content Uploader progress indicator is confusing

### ISSUE THREAD

**Issue by scherroman** [box/box-ui-elements#226]
We are using the Box Content Uploader in one of our web applications, and several of our users are telling us it does not work, saying the upload progress is always stuck at zero.

This happens because although it appears that uploading has begun, since the progress indicator is displayed once a file is selected or dropped in, they have not actually pressed the upload button yet.

<img width="788" alt="screen shot 2018-03-15 at 10 19 15 am" src="https://user-images.githubusercontent.com/7923938/37469037-c8fed1b0-283a-11e8-8d5e-d2c5e568dc4c.png">

**Comment by tonyjin** [comment]
Oof you're right. Thanks for the report, we'll work on this UX.
