### ISSUE TITLE
Any way to hide folder breadcrumb on the Content Explorer

### ISSUE THREAD

**Issue by mremigio** [box/box-ui-elements#228]
Hello:

Just curious if there is a way to hide the 'folder breadcrumb' on the Context Explorer ?

Thanks

**Comment by tonyjin** [comment]
You can with CSS: https://codepen.io/box-platform/pen/zWZBdd

This may work well for a folder with no sub-folders, but once you have sub-folders and navigate into one of those sub-folders, there will be no way to go back to the parent.

**Comment by tonyjin** [comment]
Oops, you probably can't reply if the issue is closed.

**Comment by mremigio** [comment]
Hi tonyjin:

Is there a way to hide the 'folder breadcrumb' only, but, still show the 'Upload' documents feature ?

Thanks
Mila

**Comment by mremigio** [comment]
Never mind.  It seems changing .btn-plain css works.
Thank you

**Comment by tonyjin** [comment]
I'd suggest you change the CSS for `.be-breadcrumbs` instead. `.btn-plain` is meant for plain styling on a generic button and we may use that class for other elements.

**Comment by mremigio** [comment]
Sounds good. Thank tonyjin
