### ISSUE TITLE
Content Explorer Should Wrap Text in Delete Dialog

### ISSUE THREAD

**Issue by stevebingsoo** [box/box-ui-elements#2323]
**Environment:**

- Elements version: All versions

**Desktop (please complete the following information):**

- OS: All OS
- Browser: all browsers
- Version: all versions

**Steps to reproduce the problem:**
Attempt to delete a file with a very long name

**What is the expected behavior? (Screenshots can be helpful here)**
Filename in the delete dialog should wrap

**Screenshots**
![Screen Shot 2020-09-03 at 11 23 43 AM](https://user-images.githubusercontent.com/6386688/92141670-5bf93900-edd8-11ea-87be-1620eee6ba96.png)

**Comment by MdHusainThekiya** [comment]
is this still open?
