### ISSUE TITLE
Box Content Explorer - Print and Download buttons in preview not working

### ISSUE THREAD

**Issue by AlexJPotter** [box/box-ui-elements#233]
### Replication steps:
- Click on a file within the **Content Explorer** to preview the file
- Click on either the **Print** or **Download** buttons in the header bar

### Expected behaviour:
- A print or download dialog is displayed

### Actual behaviour:
- Nothing happens

I've tested this on the CodePen demo at https://developer.box.com/docs/box-content-explorer on both Firefox and Chrome, so it looks like this is a real bug rather than an issue with my code.

For what it's worth, it is still possible to download a file by hitting the ellipsis button (**...**) next to the file in the **Content Explorer** and selecting the **Download** option.

**Comment by jeremypress** [comment]
Hey @AlexJPotter,
We've verified the issue and will have a fix out soon. Thanks for reporting!

**Comment by jeremypress** [comment]
A fix can be found in this PR: https://github.com/box/box-ui-elements/pull/235

**Comment by priyajeet** [comment]
Should be fixed in version 4.4.0, though the print button shows up for certain file types that dont support printing.
