### ISSUE TITLE
jest test error while running test cases

### ISSUE THREAD

**Issue by mindej** [box/box-ui-elements#2345]
**Environment:**
Development

- Elements version:
"jest": "24.8.0",
"box-ui-elements": "^12.0.0",

**Desktop (please complete the following information):**

- OS: Mac

**Steps to reproduce the problem:**

create a project which is using ContentPicker
Run Test.

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**

Error:

![image](https://user-images.githubusercontent.com/1636250/94439493-29f5af80-01a9-11eb-9ecf-5ac8026654a8.png)

import 'regenerator-runtime/runtime';
^^^^^^^
SyntaxError: Cannot use import statement outside a module

**Comment by alexkrolick** [comment]
You'll need to unexclude the box-ui-elements node module from the transpilation settings in Jest, because it ships ES Modules.

**Comment by mindej** [comment]
@alexkrolick Can you be more specific?

**Comment by alexkrolick** [comment]
**jest.config.js**
```js
module.exports = {
    /* ... */
    /* Make sure jest knows to transpile the modules with babel */
    transformIgnorePatterns: [
        'node_modules/(?!(box-ui-elements)/)',
    ],
};
```
