### ISSUE TITLE
UI Content Explorer:  Add meta data to uploaded documents

### ISSUE THREAD

**Issue by mremigio** [box/box-ui-elements#238]
Hello:

Is there a way to add meta data to documents that are uploaded via the UI Content Explorer via this api:

 contentExplorer.show(folderId, accessToken, {
                container: '.container',
                logoUrl: 'box', 
                defaultView: 'files',
                canRename: false,
                canCreateNewFolder: false,
                canShare: false,
                canSetShareAccess: false,
                canPreview: true,
                canDownload: true,
                canDelete: getCanDelete(),
                canUpload: getCanUpload(),
                requestInterceptor: addExtraHeaders,
                sortBy: 'modified_at',
                sortDirection: 'DESC'

            });

Thanks

Mila

**Comment by jeremypress** [comment]
Hi @mremigio,
You can listen to the ["upload" event](https://developer.box.com/docs/box-content-explorer#section-events), and then use the [metadata endpoint](https://developer.box.com/reference#overview-2) to set metadata on the newly uploaded file.

**Comment by mremigio** [comment]
Thanks jeremypress

Do you happen to have example code to share ?

Thank you

**Comment by jeremypress** [comment]
Hi @mremigio,
Unfortunately we don't have a codepen for this example. If you have a question about the metadata API specifically, check out the [Box Developer Forum](https://community.box.com/t5/Box-Developer-Forum/bd-p/DeveloperForum).
