### ISSUE TITLE
Pass in a label prop to rename the 'Close' button in the ContentUploader

### ISSUE THREAD

**Issue by mremigio** [box/box-ui-elements#242]
Hello:

We are using the UI Content Explorer which calls the Uploader.  Is there a way for us to change the text on the Uploader's Close button to a text of our choosing ?  I tried manipulating the CSS, but, since the Uploader is in a different HTML page, it does not work.  We are using the javascript agnostic libraries.

Thanks

**Comment by jeremypress** [comment]
Hi @mremigio, can you paste the CSS that you tried? It may just be an issue with class names since you're including multiple elements.

**Comment by priyajeet** [comment]
I guess one can add button label prop to the Uploader component too, like we do for the picker
https://github.com/box/box-ui-elements/blob/master/src/components/ContentPicker/ContentPicker.js#L88

**Comment by mremigio** [comment]
I like this idea priyajeet.  Can we implement this as an enhancement ?

**Comment by jeremypress** [comment]
Hi @mremigio,
We would welcome this as a contribution if you want to submit a PR!

**Comment by mremigio** [comment]
That's wonderful jeremypress as our customers here at UCLA really want this feature.
Thanks again!

**Comment by jeremypress** [comment]
@mremigio — to be clear, we are not working on this but can help with code reviews if you’re able to submit a pull request.
