### ISSUE TITLE
Box-ui-elements: npm package issue (ReactJS)

### ISSUE THREAD

**Issue by MridulSharma20** [box/box-ui-elements#2456]
I am trying to build custom react components with the npm package 'box-UI-elements' version 12.0.0

I encountered two problems here:
1st is that the npm command "npm install box-ui-elements" does not install all the peer dependencies on its own (i.e I need to install the packages manually). Is it expected or I am missing something?

2nd is that after installing all the packages (i.e npm install node-sass axios classnames draft-js form-serialize jsuri pikaday react-animate-height  react-measure scroll-into-view-if-needed tabbable react-modal react-intl)

When I try to import any of the elements (say content-preview), I am getting the following error
./node_modules/box-ui-elements/es/components/focus-trap/FocusTrap.js
Attempted import error: 'tabbable' does not contain a default export (imported as 'tabbable').

The import statement and Code is as follows :

import ContentPreview from 'box-ui-elements/es/elements/content-preview';
import messages from 'box-ui-elements/i18n/en-US';

<ContentPreview
     hasHeader={true}
     fileId={"fileId"}
     token={"token"}
     language='en-US'
     messages={messages}
   />
Please suggest any solution.

**Comment by DerekKeeler** [comment]
I know this is old but just in case anyone else runs into this:
I can't comment on why this is happening but when you're installing the extra modules make sure you're matching the versions in the box-ui-elements package.json file. Many of these dependencies are several major versions out of date so running `npm i tabbable` results in pulling down the latest tabbale utility with an incompatible api. Instead run `npm i tabbable@1.1.3`.
