### ISSUE TITLE
boxCDN failing

### ISSUE THREAD

**Issue by addula** [box/box-ui-elements#249]
Please fill out the following template so we can reproduce and fix your issue as quickly as possible!

**Note:** if your issue includes a potential security vulnerability, please do not file it here. Instead, email the issue to security@box.com for support.

Environment:
- UI Elements version:
- Components used:
- Browser name and version:
- Operating system and version:

Steps to reproduce the problem:
1. Try loading preview
2. Attached image
3.
![image](https://user-images.githubusercontent.com/8180863/38194984-a042b72a-3698-11e8-8415-f11db13cb4dc.png)

What is the expected behavior? (Screenshots can be helpful here)

What went wrong? (Screenshots can be helpful here)
box cdn call is failing with 404
Link to application or sample code:

If relevant, link to file (or attach file here):

**Comment by priyajeet** [comment]
You are using the incorrect versions. See the latest ones here https://developer.box.com/docs/box-content-preview

**Comment by addula** [comment]
I am using `Preview.js` and `Preview.css` from LATEST `box-ui-elements` npm component.

**Comment by addula** [comment]
@priyajeet

**Comment by tonyjin** [comment]
We do not guarantee every version on npm is deployed to our CDN. Please visit our developer documentation pages (the one Priyajeet linked or https://developer.box.com/docs/box-ui-elements for Elements) to see the latest deployed version.

**Comment by addula** [comment]
@tonyjin I have dowloaded latest version that is available on NPM and using `preview.js`, `preview.css` from `dist` folder which is generated after `npm install box-ui-elements`. CDN calls that I posted in the issue are made from `preview.js` I guess (I think I am sure) which is not in my control. So, now please let me know whether to use `box-ui-elements` (for preview) or not if there is not guarantee for a stable version.

**Comment by addula** [comment]
Also, kindly keep the issue in open state unless we wrap up the discussion

**Comment by priyajeet** [comment]
Unless you are building React app that is trying to `import` (ES2015) the ui elements in this github repo via NPM, you should not be using instructions mentioned here, nor should you be using NPM. You will need to follow our docs here https://developer.box.com/docs/box-content-preview

**Comment by priyajeet** [comment]
Closing this for now, discussion can continue on https://github.com/box/box-content-preview/issues/752
