### ISSUE TITLE
"Select" button in file/folder picker should be inactive until something is selected. 

### ISSUE THREAD

**Issue by jeremypress** [box/box-ui-elements#257]
Environment:
- UI Elements version:
Latest
- Components used:
Folder/File Picker
- Browser name and version:
Any
- Operating system and version:
Any

Steps to reproduce the problem:
1. Load the file/folder picker
2. notice that the select button is active

What is the expected behavior? (Screenshots can be helpful here)
Button should be inactive, like we do with the uploader before you've dropped any content.

**Comment by DaleyKD** [comment]
I like this idea. However, we may have a use-case where zero items selected is actually important.

**Comment by yeahforbes** [comment]
There seems to be a `maxSelectable` property but not a `minSelectable` property. Sounds like this fix would require implementing `minSelectable` and then keeping the button inactive until that minimum is reached. It should probably default to 1 so most people enjoy the "fix" without additional effort but the use case @DaleyKD mentions can be accommodated.

**Comment by DaleyKD** [comment]
@yeahforbes  - LOVE IT!
