### ISSUE TITLE
Cannot Access CDN https://cdn01.boxcdn.net/platform/elements/6.0.0/en-US/explorer.js 

### ISSUE THREAD

**Issue by mremigio** [box/box-ui-elements#2648]
Please fill out the following template so we can reproduce and fix your issue as quickly as possible!

**Note:** if your issue includes a potential security vulnerability, please do not file it here. Instead, email the issue to security@box.com for support.

**Note:** if your issue involves previewing files, please report the issue [here](https://github.com/box/box-content-preview/issues/new/choose).

**Environment:**
PROD, DEV and TEST

- Elements version:
 https://cdn01.boxcdn.net/platform/elements/6.0.0/en-US/explorer.js 

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]

**Steps to reproduce the problem:**
Our website uses this CDN:  https://cdn01.boxcdn.net/platform/elements/6.0.0/en-US/explorer.js 
The contentExplorer is returning an error.
Please help, this is affecting our Production Systems

**What is the expected behavior? (Screenshots can be helpful here)**
Documents should show up.

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
We are getting an error when trying to call contentExplorer api

![image](https://user-images.githubusercontent.com/14659790/127408626-f66d6067-cc9e-46c4-b620-783d6920fe73.png)

**Link to application or sample code:**

**If relevant, link to file (or attach file here)**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by greg-in-a-box** [comment]
Please try using the latest CDN url (https://cdn01.boxcdn.net/platform/elements/15.0.0/en-US/explorer.js) and see if that works.


If the issue still exist, please open a new issue
