### ISSUE TITLE
Content Explorer: Can we change the 'modifed by'

### ISSUE THREAD

**Issue by mremigio** [box/box-ui-elements#267]
Hello:

We are using the ContentExplorer.  Is there any way we can change the 'modified_by name" to a user of our choosing via the ResponseInterceptor ?   I tried the following and it seems we cannot:

  var modifyResponse = function (response) {
  if ((response.config.method == 'get') && (response.data.item_collection != null)) {
          response.data.modified_by.name = "Mila Remigio";
   }
                
    return response;
 }
           
            contentExplorer.show(folderId, accessToken, {
                container: '.container',
                logoUrl: 'box', 
                defaultView: 'files',
                canRename: false,
                canCreateNewFolder: false,
                canShare: false,
                canSetShareAccess: false,
                canPreview: true,
                canDownload: true,
                canDelete: getCanDelete(),
                canUpload: getCanUpload(),
                requestInterceptor: addExtraHeaders,
                responseInterceptor: modifyResponse,
                sortBy: 'modified_at',
                sortDirection: 'DESC',
                size: 'small'

            });

Environment:
UI Elements version: https://cdn01.boxcdn.net/platform/elements/4.3.2/en-US/explorer.js"
Components used: Content Explorer
Browser name and version: Chrome
Operating system and version: Windows 10

Thanks

**Comment by jeremypress** [comment]
Hi @mremigio, 
You'll need to modify the data of each entry, not of the response as a whole.

e.g. response.data.item_collection.entries <- change modified_at.name of these items

**Comment by mremigio** [comment]
Thanks for the feedback jeremypress.
But, for some reason, the 'modified by' is still not changing.
However, I am able to change the name of the file.

 var modifyResponse = function (response) {
if ((response.config.method == 'get') && (response.data.item_collection != null)) {
      response.data.item_collection.entries[0].modified_at.name = "Mila"; //Doesn't work
      response.data.item_collection.entries[0].name = "My File";  //Works
}    
return response;
 }

**Comment by jeremypress** [comment]
@mremigio I think you want to access modified_by, not modified_at.

Here is a codepen demonstrating a working version.
https://codepen.io/jpress/pen/BrgBJm?editors=1010

**Comment by mremigio** [comment]
This works great. Thank you jeremypress
