### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by sluther** [box/box-ui-elements#275]
Please fill out the following template so we can reproduce and fix your issue as quickly as possible!

**Note:** if your issue includes a potential security vulnerability, please do not file it here. Instead, email the issue to security@box.com for support.

Environment:
- UI Elements version: 4.4.1
- Components used: N/A
- Browser name and version: N/A
- Operating system and version: macOS High Sierra

Steps to reproduce the problem:
1. Download v4.4.1 as a .zip from github and unzip it
2. Run `npm install`
3. `npm install` missing peer dependencies

What is the expected behavior? (Screenshots can be helpful here)
Running `npm install` should not result in conflicting peer dependencies.

What went wrong? (Screenshots can be helpful here)
It complains about the following peer dependencies:
```
npm WARN box-react-ui@22.13.6 requires a peer of draft-js@^0.10.1 but none is installed. You must install peer dependencies yourself.
npm WARN box-react-ui@22.13.6 requires a peer of form-serialize@^0.7.2 but none is installed. You must install peer dependencies yourself.
npm WARN box-react-ui@22.13.6 requires a peer of immutable@^3.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN box-react-ui@22.13.6 requires a peer of mousetrap@^1.6.1 but none is installed. You must install peer dependencies yourself.
npm WARN box-react-ui@22.13.6 requires a peer of pikaday@^1.6.1 but none is installed. You must install peer dependencies yourself.
npm WARN box-react-ui@22.13.6 requires a peer of react-draggable@^3.0.4 but none is installed. You must install peer dependencies yourself.
npm WARN box-react-ui@22.13.6 requires a peer of react-immutable-proptypes@^2.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN box-react-ui@22.13.6 requires a peer of react-textarea-autosize@^5.2.1 but none is installed. You must install peer dependencies yourself.
npm WARN box-react-ui@22.13.6 requires a peer of scroll-into-view-if-needed@^1.0.7 but none is installed. You must install peer dependencies yourself.
npm WARN box-react-ui@22.13.6 requires a peer of tabbable@^1.0.5 but none is installed. You must install peer dependencies yourself.
```
To fix this, I ran `npm install --save draft-js@^0.10.1 form-serialize@^0.7.2 immutable@^3.8.1 mousetrap@^1.6.1 pikaday@^1.6.1 react-draggable@^3.0.4 react-immutable-proptypes@^2.1.0 react-textarea-autosize@^5.2.1 scroll-into-view-if-needed@^1.0.7 tabbable@^1.0.5`

This works fine, but complains about more missing peer dependencies:
```npm WARN box-ui-elements@4.4.1 requires a peer of react-textarea-autosize@^6.0.0 but none is installed. You must install peer dependencies yourself.```

This conflicts with `react-textarea-autosize@^5.2.1` which was already included above.

Running `npm install` results in conflicting peer dependencies due to a peer dependency of `box-react-ui`.

Link to application or sample code:

If relevant, link to file (or attach file here):

**Comment by priyajeet** [comment]
You should only install peer dependencies mentioned in this project's package.json

https://github.com/box/box-ui-elements/blob/master/package.json#L205

**Comment by sluther** [comment]
I still get the same error:
``` npm install --save axios@^0.18.0 box-react-ui@^22.9.0 classnames@^2.2.5 draft-js@^0.10.1 filesize@^3.6.0 form-serialize@^0.7.2 immutable@~3.7.4 jsuri@^1.3.1 lodash@^4.17.5 pikaday@^1.7.0 randomcolor@^0.5.3 react@^16.0.0 react-dom@^16.0.0 react-immutable-proptypes@^2.1.0 react-intl@^2.3.0 react-measure@^2.0.2 react-modal@^3.3.1 react-process-string@^1.2.0 react-tether@^0.6.1 react-textarea-autosize@^6.0.0 react-virtualized@^9.13.0 regenerator-runtime@^0.11.1 scroll-into-view-if-needed@^1.5.0 tabbable@^1.1.2
npm WARN box-react-ui@22.13.6 requires a peer of immutable@^3.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN box-react-ui@22.13.6 requires a peer of mousetrap@^1.6.1 but none is installed. You must install peer dependencies yourself.
npm WARN box-react-ui@22.13.6 requires a peer of react-draggable@^3.0.4 but none is installed. You must install peer dependencies yourself.
npm WARN box-react-ui@22.13.6 requires a peer of react-textarea-autosize@^5.2.1 but none is installed. You must install peer dependencies yourself.```

**Comment by priyajeet** [comment]
They are just warnings. Try running a build using `yarn build` and it should pass without errors.

**Comment by priyajeet** [comment]
@sluther One another thing, you only need to install peer deps on the project that's importing box-ui-elements. Since that's the peer. If you are just trying to build box-ui-elements project itself, you should not need to install anything additional that doesn't come automatically with npm install. Everything listed under the dev dependencies should suffice for building/testing box-ui-elements.

**Comment by tonyjin** [comment]
@sluther are you still running into issues?

**Comment by sluther** [comment]
@tonyjin thanks for following up on this. I just started working on this again today, and sure enough, it works. Thanks for all the help everyone! 👍
