### ISSUE TITLE
Refresh ContentTree component

### ISSUE THREAD

**Issue by angelsalazar** [box/box-ui-elements#286]
Hi, 

Can you provide a way to refresh the ContentTree content?
At the moment, the component does not updates when new files are uploaded.

The workaround I am using to refresh the ContentTree is to unmount and remount it, but I do not feel it is right.

**Comment by angelsalazar** [comment]
@tonyjin I saw you remove the ContentTree  docs, does this mean ContentTree is not usable for production?

**Comment by tonyjin** [comment]
We aren't maintaining it right now and don't want to encourage its usage. We haven't decided whether we want to keep it around long term yet. What's your use case?

**Comment by angelsalazar** [comment]
Good to know, I will restructure my app then.
Well I do not have a specific use case but I think of that component as a primitive that I can use to create other components.

**Comment by tonyjin** [comment]
Thanks for sharing!
