### ISSUE TITLE
TargetedClickThroughGuideTooltip with an icon does not display correctly

### ISSUE THREAD

**Issue by plaskowski** [box/box-ui-elements#2866]
Hi,
Piotr Laskowski from Box Poland here 👋 

**Environment:**

- Elements version: 15.0.0-beta.46

**Desktop (please complete the following information):**

- OS: macOS Monterey
- Browser: Chrome latest

**Steps to reproduce the problem:**
Use TargetedClickThroughGuideTooltip with a title, text and icon. The icon gets displayed above the text, not to the left of it.
![Screenshot 2022-03-29 at 09 47 26](https://user-images.githubusercontent.com/1999603/160560886-a7304635-37b9-4677-861f-16f648192c5a.png)

**Expected behaviour:**
![Screenshot 2022-03-29 at 09 38 32](https://user-images.githubusercontent.com/1999603/160559393-80681783-0b44-465d-966f-88c9d5250de6.png)

**Link to application or sample code:**
https://gist.github.com/plaskowski/4c09680cd171b537b66d19f2ca5f4367

**Comment by tjuanitas** [comment]
we took so long to address this that internal teams should now migrate to the blueprint components
