### ISSUE TITLE
Content Upload is showing status 200, but fails to load file to box account.

### ISSUE THREAD

**Issue by JohnAlfaJango** [box/box-ui-elements#2901]
Here is the box-ui-elements call that we are using (../components/ContentUploader)
import React from "react"

```
import React from "react"

import { IntlProvider } from 'react-intl';
import ContentUploader from 'box-ui-elements/es/elements/content-uploader';

function BoxFileUpload ({ props }) {
  console.log('Uploader props: ', props)
  return(
    props.project.isLoading ?
      <p>Loading...</p>
      :
      <IntlProvider locale="en">
        <ContentUploader
          language='en-US'
          token={props.project.data.attributes["box_access_token"]}
          rootFolderId={props.id}
          isFolderUploadEnabled={true}
        />
      </IntlProvider>
  )
}
export default BoxFileUpload
```
![Screen Shot 2022-05-20 at 9 37 20 AM](https://user-images.githubusercontent.com/22347430/169540406-25bd30fd-a7d6-48ef-9c84-1594caaab9ad.png)
![Screen Shot 2022-05-20 at 9 36 41 AM](https://user-images.githubusercontent.com/22347430/169540407-a73f36fa-b1a9-41dd-936c-85e0233809f8.png)
![Screen Shot 2022-05-20 at 9 36 34 AM](https://user-images.githubusercontent.com/22347430/169540408-6fbc8181-787d-4c26-834a-35b680a6c9d5.png)

What am I missing?  Thanks.

**Comment by JohnAlfaJango** [comment]
What else do you need from me to help with this issue?  Thanks.

**Comment by greg-in-a-box** [comment]
@JohnAlfaJango can you show us the request that you are receiving a 200?
