### ISSUE TITLE
Object Picker error: 'bad_request'.

### ISSUE THREAD

**Issue by Lucas-H1** [box/box-ui-elements#2934]
We are using the Object Picker from box-ui-elements 15.0.0 in a React app, but are getting persistent Bad Request errors.
The Picker does not fully load:
<img width="354" alt="Screen Shot 2022-06-17 at 3 22 20 PM" src="https://user-images.githubusercontent.com/107492680/174389296-9891b81b-3781-49c1-9825-766d7b09acd6.png">
Here is the error message.
<img width="601" alt="Screen Shot 2022-06-17 at 2 31 31 PM" src="https://user-images.githubusercontent.com/107492680/174389219-b00a696d-270a-4bf9-8064-9911588b0b98.png">

We are using the picker code at: [https://cdn01.boxcdn.net/platform/elements/15.0.0/en-US/picker.js](url).

`const picker = new Box.ContentPicker();`
`picker.show(0, accessToken, {container: ".container", chooseButtonLabel: 'Select'});`

**Comment by tjuanitas** [comment]
Hi @Lucas-H1, I think the first parameter, `0`, for `picker.show()` needs to be in quotes.

Give this a try:
```
const picker = new Box.ContentPicker();
picker.show('0', accessToken, { container: '.container', chooseButtonLabel: 'Select' });
```

**Comment by Lucas-H1** [comment]
Thank you @tjuanitas , that solved it!
