### ISSUE TITLE
Testing npm package locally

### ISSUE THREAD

**Issue by LookYgor** [box/box-ui-elements#2996]
**Note:** if your issue involves previewing files, please report the issue [here](https://github.com/box/box-content-preview/issues/new/choose).

**Environment:**
node 14

- Elements version:
- Desktop
- OS :Windows 11
- Browser chrome
- Version 104.0.5112.81 (Official Build) (64-bit)

**Steps to reproduce the problem:**
yarn start:npm
yarn link

than in the parent project 
yarn link box-ui-elements 
yarn start

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
![image](https://user-images.githubusercontent.com/103464570/184797717-885d9690-3ec4-4897-afaf-d851e96a49d0.png)

**Additional context**
It works just fine when I run/debug using the examples page but I am unable to link the package locally.

**Comment by greg-in-a-box** [comment]
We think its a webpack issue where it will attempt to transpile `node_modules/box-ui-element` while linked which would throw that exception.  You need to `exclude` `node_modules/box-ui-elements` from webpack ([doc](https://webpack.js.org/configuration/module/#ruleexclude))

**Comment by LookYgor** [comment]
I have added node_modules/box-ui-elements from webpack but I am still getting the same error. [Repo](https://github.com/LookYgor/import-error)
