### ISSUE TITLE
Update node.js to v18 and npm to v8

### ISSUE THREAD

**Issue by ASDAlexey** [box/box-ui-elements#3100]
We use box-ui-elements as an external lib in our project.
Box lib does not allow us to update our project node.js to v18 and npm to v8. Please update box-ui-elements engines to latest node.js

**Comment by micahjonas** [comment]
Same issue for us. We use box for our software platform and were using box-ui-elements version 15.0.0 as part of that. I wanted to update to version 16.0.0 but it's not possible because we are using node v18 & npm v8.

**Comment by csutorasr** [comment]
The required engines are only needed for development, but not while using the release.

Can you remove that part of the `package.json` before uploading the package?

**Comment by csutorasr** [comment]
I made this PR to remove that part of the `package.json` before uploading to the registry. I need a review on that.

@greg-in-a-box you are show here as a participant. Can you check it or ask any other maintainer to do it?

**Comment by ASDAlexey** [comment]
> ci: remove package.json engines from production build

no need to remove engines, need to update it latest support like:
"node": "^14.20.0 || ^16.13.0 || >=18.10.0"

For that need to check project update all libs in project to support  ^14.20.0 || ^16.13.0 || >=18.10.0"

This feature need not only for development, for release it needed to because we make build based on node version in engines section package.json

All modern libs(angular, react) have section need update this to and check all project tests for all works fine - it is necessary that the box-ui-elements command does this periodically. This is a good tone of libraries
"engines": {
      "node": "^14.20.0 || ^16.13.0 || >=18.10.0",

**Comment by ASDAlexey** [comment]
For update to angular 16 need minimum node.js 16.3(https://github.com/angular/angular/blob/16.0.0-next.2/package.json)
In 1 month angular 16 will be released plz update box.com 
Only because of we use box.com we can't update angular to latest version

**Comment by andrew-caines** [comment]
Is there a plan to update the box-elements-ui to support LTS nodejs and React 18.  Both of those are defacto standard at this point. (both LTS).  Currently, it will not install.

code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: client@0.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0-alpha || ^17.0.1" from @box/react-virtualized@9.22.3-rc-box.6
npm ERR! node_modules/@box/react-virtualized
npm ERR!   peer @box/react-virtualized@"9.22.3-rc-box.6" from box-ui-elements@17.0.0
npm ERR!   node_modules/box-ui-elements
npm ERR!     box-ui-elements@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:

Please advise, 
Thank you!
