### ISSUE TITLE
Box Content Explorer UI - Soft delete?

### ISSUE THREAD

**Issue by twiga2013** [box/box-ui-elements#3113]
Box Content Explorer UI delete moves the file to trash. How to move the file that was trashed to a new location folder even though original folder exist. We need a Soft Delete functionality using the Box Content Explorer. Or a solution to approach the soft delete use case.

**Comment by greg-in-a-box** [comment]
Can you elaborate what you mean by "soft delete" with a give use case?

**Comment by greg-in-a-box** [comment]
Submit new issue if use case is still valid
