### ISSUE TITLE
I have used showAnnotationsControls: true, option in preview props, so while previewing i am able to see all annotation options but not able to use them 

### ISSUE THREAD

**Issue by ayush-9** [box/box-ui-elements#3215]
I have used showAnnotationsControls: true, option in preview props, so while previewing i am able to see all annotation options but not able to use them

**Comment by greg-in-a-box** [comment]
`showAnnotationsControls:true` only shows the annotation controls in the toolbar, you have to have `showAnnotations:true` also to have them render.
