### ISSUE TITLE
Cannot read properties of undefined (reading 'pageX')

### ISSUE THREAD

**Issue by csutorasr** [box/box-ui-elements#3408]
**Environment:**

- Elements version: 2.95.0

**Smartphone (please complete the following information):**

- Device: unknown
- OS: Android
- Browser Chrome
- Version unknown

**Steps to reproduce the problem:**

Render the preview element.

**What is the expected behavior? (Screenshots can be helpful here)**

Not to throw error.

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**

```
Cannot read properties of undefined (reading 'pageX')
at n.valuein https://cdn01.boxcdn.net/platform/preview/2.95.0/en-US/preview.js
Line 33 : Column 693712
```

**Link to application or sample code:**

Private repository using the react element renderer.

**Comment by greg-in-a-box** [comment]
We do not support older versions of box-ui-elements, please use the latest version of box-ui-elements.

**Comment by tjuanitas** [comment]
@csutorasr could you try version `2.102.0` and see if the issue is resolved?
https://github.com/box/box-content-preview/releases

**Comment by csutorasr** [comment]
@tjuanitas I use that version loaded by the `box-ui-elements@18.1.0`. Can you release a new version of this library that loads the newer version of the content preview?
