### ISSUE TITLE
shaka is not defined

### ISSUE THREAD

**Issue by buraian** [box/box-ui-elements#3505]
I am using Content Explorer installed via the Box CDN and it works fine except videos will not play/preview. The error I receive is "shaka is not defined". 

To troubleshoot I tried installing the Shaka video player via CDN but it did not fix.

Please help! Thanks

**Environment:**

- Elements version: 19.0.0

**Desktop (please complete the following information):**

- OS: MacOS

**What is the expected behavior? (Screenshots can be helpful here)**

![Screenshot 2024-02-02 at 4 29 27 PM](https://github.com/box/box-ui-elements/assets/7258147/a6d4f4af-19c1-4d48-883c-5a4dc2370b83)

**Comment by greg-in-a-box** [comment]
Hey @buraian, can you verify that you can see a network request for `shaka-player.complied.js` coming from our CDNs when you preview a video?

**Comment by buraian** [comment]
Hey @greg-in-a-box, I am _not_ seeing a network request for that file or any file with the name `shaka`.

**Comment by greg-in-a-box** [comment]
<img width="989" alt="image" src="https://github.com/box/box-ui-elements/assets/103291617/c503e679-24d7-491e-a3c9-0638863a958b">
Something of this nature should be called 

I checked out our [demo](https://opensource.box.com/box-ui-elements/#/Elements/ContentExplorer) and I can see that file being loaded in. 

There are few things you could check:

1. if you are using the default preview version within the ContentExplorer or lower?
2. if your firewalls are blocking our CDNs?
3. do you see any other request from our domain that get requested, like if you open a PDF, do you see the `pdf.min.js` in the network?  `pdf.min.js` should be coming from the same domain as the `shaka-player.complied.js` just different folder

**Comment by greg-in-a-box** [comment]
We are unable to reproduce the issue, are you able to provide any codepens or sample code to reproduce this?
