### ISSUE TITLE
On second attempt to select a file, the file was not seen loaded and prepared for upload.

### ISSUE THREAD

**Issue by kshatalov** [box/box-ui-elements#351]
On second attempt to select a file, the file was not seen loaded and prepared for upload.

**Environment:**
Preview version: DEV 4.4.1

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Chrome
 - Version 66.0.3359.139

**Steps to reproduce the problem:**
1.	Go to a dataroom then click + icon
2.	Click on Upload
3.	Select file (i.e. File1.pdf)
4.	Click on Upload
5.	User decides to cancel download – click Cancel Uploads OR the “x” icon beside the file selected
6.	User decides to select a file again – clicks “browse your device”
7.	User decides to go with the same file (i.e. File1.pdf) he/she initially selected, so user selects this file again --> Nothing happens (screen should show that the file should be seen selected and is ready for upload, like in Step 5)

**Comment by priyajeet** [comment]
I think this may have been fixed by #297 
And should be part of v5 releases...

**Comment by yeahforbes** [comment]
Our experience is that this is still an open issue. The steps to reproduce are still valid.

**Comment by yeahforbes** [comment]
@priyajeet Our experience is that this is still an open issue. The steps to reproduce are still valid.
