### ISSUE TITLE
Content Explorer Destroys Bootstrap Styles

### ISSUE THREAD

**Issue by dtrodger** [box/box-ui-elements#3515]
This has been an issue for years. Please look into it.

Before integrating box-ui-elements
![Screenshot 2024-03-14 at 4 25 12 PM](https://github.com/box/box-ui-elements/assets/16841791/ab63aa06-3ff2-4f39-aaf4-0f4acf873e68)

After integrating box-ui-elements
![Screenshot 2024-03-14 at 4 25 23 PM](https://github.com/box/box-ui-elements/assets/16841791/998fe54b-368d-4411-b786-5d8bf672f759)

**Comment by greg-in-a-box** [comment]
We are aware of the issue, there is already a solution prepared, it just has yet to be applied to the elements yet
