### ISSUE TITLE
Pass a message back to the containing application when a user completes the signing process using an embedded iframe

### ISSUE THREAD

**Issue by dread-pirate-johnny-spaceboots** [box/box-ui-elements#3547]
**Describe the solution you'd like**
When embedding a signing request iframe it would be useful to be able to detect in the containing application when a user has completed the process.

I would like you to use the postMessage interface to pass a message back to the containing application on signing completion.

**Describe alternatives you've considered**
1. Positioning an invisible element above your sign & finish button to capture the click event, start a process of polling your APIs status endpoint, then removing the element and generating a new click event at the same coordiantes to hit your sign & finish button
2. Creating a browser extension to intercept your iframes HTTP requests and inspect the response to confirm signing has been completed

**Additional context**
The application I'm working on that consumes box is displaying the iframe inside a modal and when the user finishes the process we need to be able to close the modal automatically.

**Comment by greg-in-a-box** [comment]
this should be report to customer support or the forums since this is in relation to embedding widgets
