### ISSUE TITLE
Clear the search string via backspace and results based on initial search string still displayed.

### ISSUE THREAD

**Issue by kshatalov** [box/box-ui-elements#356]
Please fill out the following template so we can reproduce and fix your issue as quickly as possible!

**Environment:**
- Preview version: DEV 4.4.1

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Chrome
 - Version 66.0.3359.139

**Steps to reproduce the problem:**

The bug is built in to the box component. Even I tried on the demo link for the component (the following link) same bug occurred:

https://developer.box.com/docs/box-content-picker#section-file-selection-demo

To reproduce the bug, first try to search for a keyword and then use backspace to delete letters one by one slowly. When the whole keyword is cleared the result is what expected. But if you use backspace very fast, by deleting the whole keyword, the bug shows up.

**Comment by jeremypress** [comment]
Hey @kshatalov, thanks for reporting. We'll take a look shortly.

**Comment by jeremypress** [comment]
https://github.com/box/box-ui-elements/pull/357
