### ISSUE TITLE
Official Box documentation CDN v21.0.0 not working

### ISSUE THREAD

**Issue by olegarg1** [box/box-ui-elements#3599]
I am trying to integrate Box file picker in my next js project and was going to use CDN from the official site documentation. I got react 18.2.0 in the project and see that v21.0.0 is available in this case but clicking on every CDN in the doc gives an error message :
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>

It looks for me that there is no content available.

Official docs:
https://developer.box.com/guides/embed/ui-elements/installation/

**_If you are a Box employee, you do not need to create an issue to open a pull request_**

Please fill out the following template so we can reproduce and fix your issue as quickly as possible!

**Note:** if your issue includes a potential security vulnerability, please do not file it here. Instead, email the issue to security@box.com for support.

**Note:** if your issue involves previewing files, please report the issue [here](https://github.com/box/box-content-preview/issues/new/choose).

**Environment:**

- Elements version:

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]

**Smartphone (please complete the following information):**

**Steps to reproduce the problem:**

**What is the expected behavior? (Screenshots can be helpful here)**

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**

**Link to application or sample code:**

**If relevant, link to file (or attach file here)**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by greg-in-a-box** [comment]
Hello @olegarg1, is there any particular reason why you aren't using npm package instead of the CDN since you're using nextJS?  The CDNs should not be affected by the react update.

**Comment by olegarg1** [comment]
Hi @greg-in-a-box , thanks for your response. My project is large and using npm package will add unnecessary stuff to it as i need to use only file picker and CDN seems the right option to use in my case but when clicking on it in docs, shows error. When change to previous version in url (20.0.0) it shows ok but not the 21.0.0. I checked all the other CDN a
nd it shows the  same error . Only Content Preview  SDK is working there.

**Comment by greg-in-a-box** [comment]
The documentation for the CDNs was prematurely updated, you can use v20, the picker should be the same in both versions

**Comment by olegarg1** [comment]
Thanks @greg-in-a-box . How about using v20 for next js with react 18.2.0. I see that you have just recently updated to support react 18?

**Comment by greg-in-a-box** [comment]
v21 deployed to the CDNs

**Comment by olegarg1** [comment]
Hi @greg-in-a-box ! Great, thank you very much for confirming. I checked and this time i can see it is working. Yes , I would need to use the one with react as the other one giving me an error as it does not see React. I would need to make react available globally for that. So, I would go for v21 in this case. Thank you!
