### ISSUE TITLE
Example of Usage with Next.js

### ISSUE THREAD

**Issue by trevordebard** [box/box-ui-elements#3727]
Are there any samples on how to use this library with Next.js. Since this is the most popular React framework today, it would be helpful to have a sample repo on how to setup. 

The current guide does not provide enough information on how to resolve peer dependency issues and configuration for Next.js. Leading to a difficult experience getting set up quickly.

**Comment by greg-in-a-box** [comment]
This monorepo demo was created to provide some additional information please check it out and let use know if there is anything else that are not mentioned that should be 

https://github.com/box/box-ui-elements-monorepo-demo
