### ISSUE TITLE
Cannot resolve lodash/noop

### ISSUE THREAD

**Issue by the-marolie** [box/box-ui-elements#3739]
**Environment:**

- Elements version: 22

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 130

I'm not able to use the latest box-ui-elements v22.0.0. I get the the following error in my react app:
`Can't resolve 'lodash/noop'` in `@box/blueprint-web` components.

![image](https://github.com/user-attachments/assets/60d33f6e-257a-4697-9898-5bb644d47eee)

**Expected behavior**
The app compiles without any errors

**Additional context**
I have added all the peer dependencies as per the package.json file. 
I'm using react 18

**Comment by greg-in-a-box** [comment]
https://stackoverflow.com/questions/70964723/webpack-5-in-ceate-react-app-cant-resolve-not-fully-specified-routes

The first answer with the code block about fullySpecified shoule be set to false via the webpack.
