### ISSUE TITLE
how to change text in logo

### ISSUE THREAD

**Issue by prashantharshi** [box/box-ui-elements#400]
We have rendered the content picker for type as folder , so we are successfully getting the desired view , but we need to change text in the logo , we want to set our own custom message there 

1) is that doable via props ?
2) if we cant  , can we disable/remove that logo section

`const FolderSelectionView = (props) => {
    
    const onSelect = (folderObj) => {
        props.onfolderselection(folderObj[0].id)
    }

    return (
        <App signuseremail = {props.signuseremail}>
            <ContentPicker
                token={props.boxaccesstoken}
                language='en-us'
                type='folder'
                maxSelectable={1}
                onChoose = {onSelect}
                messages={messages}
            />
        </App>
    )
    
};`

**Comment by priyajeet** [comment]
Use the `logoUrl` prop. Point it to your logo.

**Comment by DanDeMicco** [comment]
Were you able to resolve your issue?
