### ISSUE TITLE
Removing files completely in the folder content picker

### ISSUE THREAD

**Issue by prashantharshi** [box/box-ui-elements#413]
We are using content picker with type as folder so that it renders the folder list , but in the view it has also the listing of files which are shown as disabled , do we any affordance to completely ignores or not allow the files to appear at all in the folder picker via some props

` <ContentPicker
                token={props.boxaccesstoken}
                language='en-us'
                type='folder'
                maxSelectable={1}
                onChoose = {onSelect}
                messages={messages}
                logoUrl = {UiStrings.getTranslatedString('folderSelect')}
            />`

**Comment by DanDeMicco** [comment]
Closing this issue as you opened #419 to follow up with responseInterceptor usage
