### ISSUE TITLE
Uploads continue after Content Uploader is unmounted

### ISSUE THREAD

**Issue by scherroman** [box/box-ui-elements#459]
**Environment**
- Elements version: 4.4.1

**Desktop**
 - OS: macOS High Sierra Version 10.13.1
 - Browser: Chrome Version 67

**Steps to reproduce the problem**
1. Mount the Content Uploader UI Element
2. Begin one or more uploads
3. Unmount the Content Uploader UI Element
4. Uploads unexpectedly continue and run to completion behind the scenes

**What is the expected behavior?**

When the Content Uploader is unmounted, In-progress uploads should be cancelled.

**What actually happened / went wrong?**

Uploads continue and run to completion. Any registered onUpload callbacks are fired, but because the callback often relies on / interacts with the state of a parent component that has also been unmounted (such as a modal), the callback fails, and the upload is not properly registered by our app. This is especially problematic when uploading with a Content Explorer, as the user will see files in the content explorer that were never successfully registered with our app.

**GIF of issue when using Content Explorer**

![upload continues on unmount](https://user-images.githubusercontent.com/7923938/42727631-7643e490-8778-11e8-850e-34ff8f54419a.gif)

**Comment by jeremypress** [comment]
https://github.com/box/box-ui-elements/pull/464 This make fix the issue but I need to test in an environment where the content uploader can be destroyed mid upload.
