### ISSUE TITLE
Getting "part_digest_retries_exceeded" error when uploading file with size > 50mb with Content Uploader

### ISSUE THREAD

**Issue by MaximeMarck** [box/box-ui-elements#466]
Elements version: 4.4.0

Desktop:
 - OS: Windows 7
 - Browser: Chrome
 - Version: 67

Steps to reproduce the problem:
1. Create an HTML page to display a Content Uploader such as the one provided by documentation https://codepen.io/box-platform/pen/QvqGwr
2. Update the ACCESS_TOKEN to use a generated Developer Token 
3. Go to the page and try to upload a document with a size greater than 50 Mb

What is the expected behavior? 
Document should be uploaded.

What went wrong?
Content uploader displaying "Something went wrong with the upload. Please try again".

In the Network tab of the console, I can see that a call is made to https://upload.box.com/api/2.0/files/upload_sessions and the server sends back a response with the parts and endpoints.

Then normally several calls are made to endpoints to send documents but nothing here.
After a few minutes 2 calls are made to https://upload.box.com/api/2.0/files/upload_sessions/[ID]/log 
with this request payload: {"event_type":"part_digest_retries_exceeded","event_info":"{}"}

Then a HTTP Delete is issued to https://upload.box.com/api/2.0/files/upload_sessions/[ID]

Additional context:
The page is hosted on an internal server named http://webtest/sitename
http://webtest was added to the CORS allowed origins.
Small files uploads works properly.

Same page works in Internet Explorer 11 and Firefox.
It doesn't work in Chrome. 

The Codepen example works properly in Chrome so it seems to be related to the fact that the Content Uploader is hosted on an internal server?

**Comment by DanDeMicco** [comment]
Hey @MaximeMarck this was fixed in v5.0 https://github.com/box/box-ui-elements/releases, can you try updating your version to v5.1.0 https://cdn01.boxcdn.net/platform/elements/5.1.0/en-US/uploader.js

**Comment by DanDeMicco** [comment]
Thats strange it works everywhere but your server. When you tried 5.1.0 on your server, did you use the CDN or npm? 

Can you try seeing what the error messages are in the console? You should be able to send ```consoleError:true```  as a prop when initializing

**Comment by DanDeMicco** [comment]
Just investigated this with @wenboyu2 it seems for whatever reason, when you are not using localhost, the upload fails when your server that is hosting the uploader is not on HTTPS. Can you try changing your local server to use HTTPS and give it another shot?

**Comment by wenboyu2** [comment]
@MaximeMarck When uploading files larger than 50MB we use 'Chunked Upload' strategy for better upload performance. Chunked Upload expects `window.crypto.subtle` to be available, which is not when the connection to a site is not secure.

I'll submit a PR to allow large file upload to fallback to normal file upload when `window.crypto.subtle` is not available. 

We recommend enabling HTTPS for your website for the improved large file upload performance.

**Comment by MaximeMarck** [comment]
@DanDeMicco : yes I tried to host my app on a test server with HTTPS enabled and 50Mb+ uploads are now working properly in Chrome as well now. Thanks

@wenboyu2 : thanks for for the technical details and the PR to support the fallback scenario.

Thanks to both of you for your quick answer. Let me now if should close this issue or if you want to leave it empty until the PR is available

**Comment by DanDeMicco** [comment]
Should fall back/display a warning message in v6.2.0 or later
