### ISSUE TITLE
addListener for `ContentUploader` Events not firing 

### ISSUE THREAD

**Issue by adamgins** [box/box-ui-elements#524]
Hi, for some reason the `upload` and `complete` events are not firing when a user selects them in the embedded Box UI (html/js) in the Buzzy UI. It works fine for the `picker` just the `uploader` is misbehaving.

perhaps related, Also in the picker I cannot "add new" with the "+" icon. 

Box API versions loaded
```
<script src="https://cdn01.boxcdn.net/platform/elements/6.0.0/en-US/picker.js"></script>
	<script src="https://cdn01.boxcdn.net/platform/preview/1.49.0/en-US/preview.js"></script>
	<script src="https://cdn01.boxcdn.net/platform/elements/6.0.0/en-US/uploader.js"></script>
```

The weird thing is it's working with Box.FilePicker() but not with Box.ContentUploader()

I actually copied my code from the picker to create the uploader files, changed params.

My files get uploaded, but I never get the 'upload' or complete events, I do get the 'close' event.

Any ideas what would prevent the ContentUpload from sending me these events?

here's my code

I am loading

        <script src="https://cdn01.boxcdn.net/platform/elements/6.0.0/en-US/picker.js"></script>
	<script src="https://cdn01.boxcdn.net/platform/preview/1.49.0/en-US/preview.js"></script>
	<script src="https://cdn01.boxcdn.net/platform/elements/6.0.0/en-US/uploader.js"></script>
then when the document is rendered...

var folderId = '0';

  	var boxContentUploader = new Box.ContentUploader();
  	boxContentUploader.show(folderId, accessToken, {

        container: '.box-uploader-container',

    });
    boxContentUploader.addListener('upload', function(file){
        console.log('upload',file, parentTemplateData);
		
    });
    boxContentUploader.addListener('complete', function(files){
        console.log('complete',files, parentTemplateData);
		
    });
    boxContentUploader.addListener('error', function(error){
        console.log('error',error);
 
    });
    boxContentUploader.addListener('close', function(){
        console.log('cancel');
     
    });
Any help appreciated

**Comment by DanDeMicco** [comment]
Hi @adamgins if you are unable to provide us a codepen to reproduce the issue, it would be best if you contact Box support. Closing the issue for now, but feel free to reopen if you are able to provide a codepen which reproduces the issue.

**Comment by rdiaznasser** [comment]
@adamgins were you able to figure this out? Hitting the same issue as you! What is strange is that it works fine when iframing through HTML(Visualforce), but breaks when implementing it in Salesforce's Lightning Components. The events aren't fired back up.
