### ISSUE TITLE
Preview takes a huge time to load

### ISSUE THREAD

**Issue by amulgarg** [box/box-ui-elements#527]
Using the **ContentPreview** component, any document takes a huge amount to load. Furthermore, every page of the file takes at least 4 seconds after the initial load.

**Environment:**
- Elements version:

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser Google Chrome
 - Version 67.0.3396.99

**Steps to reproduce the problem:**
1. Upload a PDF file (or any other file, though I tried with PDF) to Box and get the File ID
2. Try to show a preview in your React app using the **ContentPreview** Component
3. Scroll through the pages.

**What is the expected behavior? (Screenshots can be helpful here)**
Faster load

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
Long wait time to see the page

**Comment by DanDeMicco** [comment]
Hi @amulgarg can you please prove us a .har?

**Comment by amulgarg** [comment]
Hi @DanDeMicco 
.har files for two documents I tried
1. https://knolskape-website.s3.amazonaws.com/misc/amul_garg/2018/09/18/2/box_preview1.har
2. https://knolskape-website.s3.amazonaws.com/misc/amul_garg/2018/09/18/49/box_preview2.har

Thanks

**Comment by amulgarg** [comment]
Hey @DanDeMicco 
Did you have a chance to check the .har files I sent?

**Comment by jstoffan** [comment]
Hi @amulgarg. We're going through our issues. Are you still experiencing issues with Preview load times? The HAR files attached don't seem to want to load for me.
