### ISSUE TITLE
How to hide Printer and Download images in Preview Mode

### ISSUE THREAD

**Issue by mremigio** [box/box-ui-elements#528]
Description of the Issue
We are using Explorer via: https://cdn01.boxcdn.net/platform/elements/4.3.2/en-US/explorer.css. In Preview, is there a way to hide Printer and the Download image since they don't work.

Versions Used
.NET Framework 4.6

Steps to Reproduce
Using Explorer, preview a document

Error Message, Including Stack Trace
N/A

**Comment by DanDeMicco** [comment]
Hi @mremigio I would recommend updating to the latest elements release (6.1). I just validated the print and download work there.

**Comment by mremigio** [comment]
Hi DanDeMicco:
I tried these links and getting errors:
https://cdn01.boxcdn.net/platform/elements/6.1/en-US/explorer.css
https://cdn01.boxcdn.net/platform/elements/6.1/en-US/explorer.js

**Comment by DanDeMicco** [comment]
Hi @mremigio sorry, please use 6.0

**Comment by mremigio** [comment]
6.0 works. Thanks DanDeMicco
