### ISSUE TITLE
ContentExplorer creates a huge bundle 

### ISSUE THREAD

**Issue by vb** [box/box-ui-elements#530]
Adding the ContentExplorer adds **326.93 kb** to the bundle. This can't be right, can it?

**Environment:**
- "box-ui-elements": "^6.1.0"

**Desktop (please complete the following information):**
 - OS: OSX

**Steps to reproduce the problem:**
1. Install a react boilerplate
```
create-react-app box-ui-elements-test
cd box-ui-elements-test
```
2. Install box-ui-elements and peerDependencies
```
// Install box-ui-elements
yarn add box-ui-elements

// Install peerDependencies
yarn add axios box-react-ui classnames draft-js filesize form-serialize immutable jsuri lodash pikaday react react-dom react-immutable-proptypes react-intl react-measure react-modal react-process-string react-tether react-textarea-autosize react-virtualized regenerator-runtime scroll-into-view-if-needed tabbable
```

3. Install missing dependency
```
yarn add react-animate-height
```

4. Build a initial build without including ContentExplorer
```
yarn build
```

5. Add ContentExplorer to `src/App.js`
```js
// src/App.js
import React, { Component } from 'react';
import { ContentExplorer } from 'box-ui-elements';
import logo from './logo.svg';
import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
        <ContentExplorer />
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
    );
  }
}
```

6. Create a new build
```
yarn build
```

7. Verify that the build has increased by 326.93 kb

**What is the expected behavior? (Screenshots can be helpful here)**
I expect the bundle to not increase by that much

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
The bundle increases too much and there is a missing dependency from peerDependencies

**Comment by priyajeet** [comment]
One thing that may be unnecessarily getting bundled is moment.js which is big.
You can shim it out via aliasing it in webpack config like we do https://github.com/box/box-ui-elements/blob/master/build/webpack.config.js#L57
