### ISSUE TITLE
iOS search input border-radius inconsistent in Content Picker

### ISSUE THREAD

**Issue by bighitbiker3** [box/box-ui-elements#546]
I'm not seeing anywhere in the source that would cause this but if this was intentional please let me know. 

**Environment:**
- Elements version: 6.x

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone SE and iPad
 - OS: 11 & 12
 - Browser Safari

**Steps to reproduce the problem:**
1. Open 
https://codepen.io/box-platform/full/PWPxBm/ on your iPhone or iPad
2. Search input has significant border radius until you focus on it (See gif)
3.

**What is the expected behavior? (Screenshots can be helpful here)**
Border radius should stay consistent

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**

![giphy](https://user-images.githubusercontent.com/15604901/45391186-e4bcb000-b5d6-11e8-8823-f85c21fe525c.gif)

**Comment by DanDeMicco** [comment]
Hey @bighitbiker3 thanks for the report. I was able to verify the issue and put it on our backlog. If you would like to contribute a fix, feel free!

**Comment by matthewdfleming** [comment]
I worked around this by overriding the css:
`.be input {
    -webkit-appearance: none !important;
}`
