### ISSUE TITLE
Drag and drop download files to desktop

### ISSUE THREAD

**Issue by Band-Aid** [box/box-ui-elements#591]
- Raising this on behalf of customer
**Describe the solution you'd like**
I would like to be able to drag and drop files from the Explorer to UI to my local desktop.
In the box web app, you are able to do this by Selecting a file and holding cmd/cntrl and drag the file from the web browser over to the desktop

**Describe alternatives you've considered**
box Web app/

**Additional context**
If you're already a Box customer, please send an email preview-team@box.com with your admin's information/enterprise ID.

**Comment by jstoffan** [comment]
Hi @Band-Aid. We don't have any near-term plans to add this behavior to Content Explorer, but I will forward your feedback to our product team. Thank you!
