### ISSUE TITLE
Response Interceptor Error Detection

### ISSUE THREAD

**Issue by matthewdfleming** [box/box-ui-elements#627]
Could you please add some documentation around how to detect a true error from the responseInterceptor function? This is my function now but it's been a bit of trial and error

```
responseInterceptor: (response) => {
    if (response && response.status === 200) {
      // all good
    } else if (response && response.status) {
        this.onError(response);
    } else {
       // this is what I used to think was an error but it seems to happen during normal file viewing
    }
    return response;
}
```
**Environment:**
- Elements version: 8.0.0

**Comment by DanDeMicco** [comment]
A success is not necessarily just a 200. It could be a 20X (such as 204) depending on which element you are using and which API it calls. I think in general it should be successful if status >= 200 && status < 300

**Comment by DanDeMicco** [comment]
You can also look at https://github.com/axios/axios#handling-errors for more info
