### ISSUE TITLE
Doc Bug - Installation prerequisites

### ISSUE THREAD

**Issue by rwjlewisbox** [box/box-ui-elements#704]
Please update the installation instructions to include requirements such as react.

Please fill out the following template so we can reproduce and fix your issue as quickly as possible!

**Note:** if your issue includes a potential security vulnerability, please do not file it here. Instead, email the issue to security@box.com for support.

**Note:** if your issue involves previewing files, please report the issue [here](https://github.com/box/box-content-preview/issues/new/choose).

**Environment:**
- Elements version:

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]

**Smartphone (please complete the following information):**

**Steps to reproduce the problem:**
1.
2.
3.

**What is the expected behavior? (Screenshots can be helpful here)**

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**

**Link to application or sample code:**

**If relevant, link to file (or attach file here)**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by DanDeMicco** [comment]
All dependencies are located in the package.json
