### ISSUE TITLE
Is Internet Explorer still supported

### ISSUE THREAD

**Issue by mremigio** [box/box-ui-elements#767]
Hello Box Team:

Today we just realized that IE 11 browser is no longer working with the Box-UI-Elements.
The following CDNs are throwing javascript errors in IE 11

https://cdn.polyfill.io/v2/polyfill.min.js?features=es6,Intl
https://cdn01.boxcdn.net/platform/elements/6.0.0/en-US/explorer.css
https://cdn01.boxcdn.net/platform/elements/6.0.0/en-US/explorer.js

However, everything works great on Chrome, Firefox, eDGE browsers.

Thanks

Mila

**Comment by jeremypress** [comment]
Hi Mila, 
We recommend including [our version of core.js](https://cdn01.boxcdn.net/polyfills/core-js/2.5.3/core.min.js) to provide IE support. 

Here is a [codepen for the explorer that uses core.js](https://codepen.io/box-platform/pen/wdWWdN), if you want to preview it in IE 11 to confirm, make sure to use the [debug URL](https://s.codepen.io/box-platform/debug/wdWWdN).
