### ISSUE TITLE
Search is not working in ContentExplorer when using a service token

### ISSUE THREAD

**Issue by joevanwanzeele** [box/box-ui-elements#780]
**Steps to reproduce the problem:**
1. https://opensource.box.com/box-ui-elements/
2. search any of the content explorer examples
3. request url is: https://api.box.com/2.0/search?offset=0&query=sa&ancestor_folder_ids=51964781421&limit=50&fields=id,name,type,size,parent,extension,permissions,path_collection,modified_at,created_at,modified_by,shared_link,allowed_shared_link_access_levels,has_collaborations,is_externally_owned,item_collection

**What is the expected behavior? (Screenshots can be helpful here)**
search works.

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
server returns 403 error:
Bearer realm="Service", error="insufficient_scope", error_description="The request requires higher privileges than provided by the access token."

**Link to application or sample code:**
https://opensource.box.com/box-ui-elements/

**Screenshots**
![image](https://user-images.githubusercontent.com/903278/51195646-86bd1380-18bb-11e9-9947-18839f35f624.png)

**Comment by jeremypress** [comment]
hi @joevanwanzeele, the token used for that examples page is intentionally limited in scope. Search should work with a service account token if you provide your own with sufficient scope. The easiest place to try that out would be to use a codepen example. https://codepen.io/box-platform/pen/wdWWdN

**Comment by hoenie-ams** [comment]
The problem still exists. You can try adding `"root_readonly"` to the scopes. See also https://github.com/box/box-ui-elements/issues/326
