### ISSUE TITLE
Is it possible to access MetaData via the file object ?

### ISSUE THREAD

**Issue by mremigio** [box/box-ui-elements#824]
Hello:

Is it possible to access Metadata from this file object (https://developer.box.com/reference#file-object).
The website says yes, but, no examples are given. 
Can you please send me examples.
Thanks

**Comment by jeremypress** [comment]
Hi @mremigio,
This issue pool is intended for issues regarding Box UI Elements. For general API questions, please use our [developer forum](https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum)
