### ISSUE TITLE
Cannot instantiate multiple ContentPreview elements at the same time

### ISSUE THREAD

**Issue by j3tan** [box/box-ui-elements#89]
Due to https://github.com/box/box-ui-elements/blob/master/src/components/ContentPreview/ContentPreview.js#L248, having multiple ContentPreview instances will only `addEventListener('load', ...)` once for the first element since subsequent elements detect the script and try calling `loadPreview` immediately.

**Comment by priyajeet** [comment]
I need to fix this anyways for the preloaded scripts use case
